-- Schoolladder: elk vak uit de officiele Nederlandse lijst.
--
-- Bron  : Waardenlijst-Vakken-en-leergebieden-po-en-vo-schooljaar-2026-2027-v1.0.xlsx
-- Gemaakt: 22 sep 2026
-- Bevat : 356 vakken en 864 examencodes
--
-- Importeer dit na database.sql. Opnieuw draaien mag: het bestand leegt eerst
-- wat het de vorige keer schreef en laat het schema de tweede keer met rust.
-- Zie docs/data.md.
--
-- Een afwijking van de bron: acht examencodes staan daar als getal en missen
-- daardoor hun voorloopnul (400, 691, 692). Alle andere codes zijn vier tekens
-- lang, dus hier staan ze als 0400, 0691 en 0692.

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

DROP TABLE IF EXISTS `subject_levels`;
DELETE FROM `subjects`;
ALTER TABLE `subjects` AUTO_INCREMENT = 1;

-- The table was built for short names. The longest name in the official list
-- is 107 characters, so varchar(30) would silently cut most of them off.
--
-- Wrapped in a check because MySQL has no ADD COLUMN IF NOT EXISTS, and this
-- file has to survive a second run.
SET @needsColumns := (
  SELECT COUNT(*) = 0 FROM information_schema.columns
   WHERE table_schema = DATABASE() AND table_name = 'subjects' AND column_name = 'prefix'
);

SET @alter := IF(@needsColumns, '
ALTER TABLE `subjects`
  MODIFY `name` varchar(150) NOT NULL,
  ADD COLUMN `prefix` varchar(60) DEFAULT NULL AFTER `abbreviation`,
  ADD COLUMN `learning_area` varchar(60) DEFAULT NULL AFTER `prefix`,
  ADD COLUMN `kind` varchar(40) DEFAULT NULL AFTER `learning_area`,
  ADD COLUMN `nickname` varchar(40) DEFAULT NULL AFTER `kind`,
  ADD COLUMN `legal_name` varchar(500) DEFAULT NULL AFTER `nickname`,
  MODIFY `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  ADD KEY `prefix` (`prefix`),
  ADD KEY `learning_area` (`learning_area`)
', 'DO 0');

PREPARE applySchema FROM @alter;
EXECUTE applySchema;
DEALLOCATE PREPARE applySchema;

-- Which subject exists at which level, with the exam code the level uses. This
-- is what answers "may a havo student take this": a subject without a havo row
-- is not on offer there.
--
-- Deliberately no unique key on code or on the subject name: the official list
-- has neither. "it" is both Italiaans and informatietechnologie, and a handful
-- of vmbo prefixes carry two names.
CREATE TABLE `subject_levels` (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `subject_id` int UNSIGNED NOT NULL,
  `level` enum('bb','kb','gl','tl','havo','vwo') NOT NULL,
  `code` varchar(10) NOT NULL,
  `exam_year_from` smallint UNSIGNED DEFAULT NULL,
  `exam_year_to` smallint UNSIGNED DEFAULT NULL,
  `sweep_year` smallint UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `subject_level` (`subject_id`, `level`),
  KEY `level_code` (`level`, `code`),
  CONSTRAINT `subject_levels_subject` FOREIGN KEY (`subject_id`) REFERENCES `subjects` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `subjects`
  (`id`, `name`, `abbreviation`, `prefix`, `learning_area`, `kind`, `nickname`, `legal_name`) VALUES
(1, 'buitenschools leren in de regio', NULL, 'ALG/blidr', 'Algemeen', NULL, NULL, NULL),
(2, 'levensbeschouwelijk vormingsonderwijs', 'lv', 'ALG/lv', 'Algemeen', NULL, 'levens vorm', 'levensbeschouwelijk vormingsonderwijs'),
(3, 'mentorles', NULL, 'ALG/ml', 'Algemeen', NULL, NULL, NULL),
(4, 'seksuele- en relationele vorming', NULL, 'ALG/srv', 'Algemeen', NULL, NULL, NULL),
(5, 'sociaal-emotionele ontwikkeling', NULL, 'seo', 'Algemeen', NULL, NULL, NULL),
(6, 'academische vaardigheden', 'acva', 'ALG/acva', 'Algemeen', NULL, 'academische vaardigheden', 'academische vaardigheden'),
(7, 'wetenschapsoriëntatie', 'weor', 'ALG/weor', 'Algemeen', NULL, 'wetenschapsoriëntatie', 'wetenschapsoriëntatie'),
(8, 'wetenschap', 'wete', 'ALG/wete', 'Algemeen', NULL, 'wetenschap', 'wetenschap'),
(9, 'product ontwerpen', 'pron', 'ALG/pron', 'Algemeen', NULL, 'prod ontwerp', 'product ontwerpen'),
(10, 'bouwen, wonen en interieur', 'bwi', 'bwi', 'Beroepsgerichte profielen BWI', 'profielvak', 'bouwwonenint', 'bouwen, wonen, interieur'),
(11, 'bouwen vanaf de fundering', 'bfun', 'P/BWI/02', 'Beroepsgerichte profielen BWI', 'profielmodule', 'bouwenfundering', 'bouwen vanaf de fundering'),
(12, 'bouwproces en bouwvoorbereiding', 'bpbv', 'P/BWI/01', 'Beroepsgerichte profielen BWI', 'profielmodule', 'bouwprocvoorb', 'bouwproces en bouwvoorbereiding'),
(13, 'design en decoratie', 'ddec', 'P/BWI/04', 'Beroepsgerichte profielen BWI', 'profielmodule', 'designdec', 'design en decoratie'),
(14, 'hout- en meubel verbindingen', 'hmvb', 'BWI/hmv', 'Beroepsgerichte profielen BWI', 'profielmodule', 'houtmeubelverb', 'hout- en meubelverbindingen'),
(15, 'aardbevingsbestendig bouwen', 'abbb', 'K/BWI/22', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'aardbevingsbestendigbouwen', 'aardbevingsbestendig bouwen'),
(16, 'bijzonder metselwerk', 'bmsw', 'K/BWI/10', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'bijzmetselwerk', 'bijzonder metselwerk'),
(17, 'bouw- en woonrijp maken', 'brwr', 'K/BWI/17', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'bouwrwoonrmaken', 'bouw- en woonrijp maken'),
(18, 'bouwkundig onderhoud, renovatie en transformatie', 'bort', 'K/BWI/05', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'bouwkonderhrenoventransf', 'bouwkundig onderhoud, renovatie en transformatie'),
(19, 'bouwmethoden bouwstijlen', 'bmet', 'K/BWI/09', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'bouwmethoden', 'bouwmethoden en bouwstijlen'),
(20, 'constructieve aansluitingen en afwerking', 'caa', 'K/BWI/01', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'constraansluitafw', 'constructieve aansluitingen en afwerking'),
(21, 'daken en kapconstructies van hout', 'dkch', 'K/BWI/07', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'dakenkapconstructieshout', 'daken en kapconstructies van hout'),
(22, 'duurzaam en circulair bouwen', 'dcb', 'K/BWI/23', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'duurzaam circulair bouw', 'duurzaam en circulair bouwen'),
(23, 'biobased en natuurlijk bouwen', 'bnb', 'BWI/bnb', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'biobased  natuurlijk bouw', 'biobased en natuurlijk bouwen'),
(24, 'gevelopeningen', 'geve', 'K/BWI/06', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'gevelopeningen', 'gevelopeningen'),
(25, 'glaszetten', 'glsz', 'K/BWI/15', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'glaszetten', 'glaszetten'),
(26, 'interieurbouw, stands en betimmeringen', 'isb', 'K/BWI/04', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'intstandbetim', 'interieurbouw, stands en betimmeringen'),
(27, 'interieurontwerp en design', 'intd', 'K/BWI/19', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'interieurontwdesign', 'interieurontwerp en -design'),
(28, 'meubelmaken', 'meub', 'K/BWI/16', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'meubelmaken', 'meubelmaken'),
(29, 'meubelstofferen voor het vmbo', 'msvv', 'K/BWI/24', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'meubelstofferen vh vmbo', 'meubelstofferen voor het vmbo'),
(30, 'onderhoud schilderwerk', 'osw', 'K/BWI/14', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'onderhschilderw', 'onderhoud schilderwerk'),
(31, 'scheidingswanden', 'schw', 'K/BWI/11', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'scheidingswand', 'scheidingswanden'),
(32, 'schilderen en spuiten op kunststof en metalen', 'sskm', 'K/BWI/13', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'schilderenspuitenkunststofmeta', 'schilderen en spuiten op kunststof en metalen'),
(33, 'schilderen van hout- en steenachtige ondergronden', 'shso', 'K/BWI/03', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'schilhoutsteen', 'schilderen van hout- en steenachtige ondergronden'),
(34, 'schoonmetselwerk', 'schm', 'K/BWI/02', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'schoonmetselw', 'schoonmetselwerk'),
(35, 'tegelzetten voor het vmbo', 'tzvv', 'K/BWI/21', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'tegelzetten voor het vmbo', 'tegelzetten voor het vmbo'),
(36, 'terreinafwerking', 'tafw', 'K/BWI/18', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'terreinafw', 'terreinafwerking'),
(37, 'vloeren', 'vloe', 'K/BWI/08', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'vloeren', 'vloeren'),
(38, 'wandafwerking', 'wafw', 'K/BWI/12', 'Beroepsgerichte profielen BWI', 'beroepsgericht keuzevak', 'wandafwerking', 'wandafwerking'),
(39, 'bouwtechniek - Infra', 'bti', 'BWI/boinf', 'Beroepsgerichte profielen BWI', 'vak met individuele licentie', 'infra', 'bouwtechniek – infra'),
(40, 'dienstverlening en producten', 'dvpr', 'dp', 'Beroepsgerichte profielen DP', 'profielvak', 'dienstverlproduct', 'dienstverlening en producten'),
(41, 'organiseren van een activiteit voor een opdrachtgever', 'oaog', 'P/DP/01', 'Beroepsgerichte profielen DP', 'profielmodule', 'organiserenactiviteitopdrachtg', 'organiseren van een activiteit voor een opdrachtgever'),
(42, 'presenteren, promoten en verkopen', 'ppv', 'P/DP/02', 'Beroepsgerichte profielen DP', 'profielmodule', 'pres,prom,verk', 'presenteren, promoten en verkopen'),
(43, 'een product maken en verbeteren', 'prmv', 'P/DP/03', 'Beroepsgerichte profielen DP', 'profielmodule', 'productmakverb', 'een product maken en verbeteren'),
(44, 'multimediale producten maken', 'mmpm', 'P/DP/04/02', 'Beroepsgerichte profielen DP', 'profielmodule', 'multimedprod', 'multimediale producten maken'),
(45, 'dans-, acteer- en zangactiviteiten', 'daza', 'K/DP/08', 'Beroepsgerichte profielen DP', 'beroepsgericht keuzevak', 'daza', 'dans-, acteer- en zangactiviteiten'),
(46, 'digispel', 'digi', 'K/DP/01', 'Beroepsgerichte profielen DP', 'beroepsgericht keuzevak', 'digispel', 'digispel'),
(47, 'geüniformeerde dienstverlening en veiligheid', 'ufdv', 'K/DP/06', 'Beroepsgerichte profielen DP', 'beroepsgericht keuzevak', 'unidienstverlveiligh', 'geüniformeerde dienstverlening en veiligheid'),
(48, 'kunstvak informatie, creatie en presentatie', NULL, 'K/DP/12', 'Beroepsgerichte profielen DP', NULL, NULL, NULL),
(49, 'milieu, hergebruik en duurzaamheid', 'mhed', 'K/DP/07', 'Beroepsgerichte profielen DP', 'beroepsgericht keuzevak', 'milieuhergebruikenduurzaamheid', 'milieu, hergebruik en duurzaamheid'),
(50, 'podium', 'podi', 'K/DP/05', 'Beroepsgerichte profielen DP', 'beroepsgericht keuzevak', 'podium', 'podium'),
(51, 'robotica', 'robo', 'K/DP/02', 'Beroepsgerichte profielen DP', 'beroepsgericht keuzevak', 'robotica', 'robotica'),
(52, 'talentvak acteren zang en dans', 'tazd', 'K/DP/09', 'Beroepsgerichte profielen DP', 'beroepsgericht keuzevak', 'tazd', 'talentvak acteren zang en dans'),
(53, 'voeding en beweging', 'vdbw', 'K/DP/04', 'Beroepsgerichte profielen DP', 'beroepsgericht keuzevak', 'voedingenbeweging', 'voeding en beweging'),
(54, 'werken aan natuur en milieu', 'wanm', 'K/DP/03', 'Beroepsgerichte profielen DP', 'beroepsgericht keuzevak', 'werkenaannatuurenmilieu', 'werken aan natuur en milieu'),
(55, 'woonhuisbeveiliging', NULL, 'DP/whb', 'Beroepsgerichte profielen DP', NULL, NULL, NULL),
(56, 'acteren en zingen', 'aczi', 'K/DP/11', 'Beroepsgerichte profielen DP', 'beroepsgericht keuzevak', 'acteren en zingen', 'acteren en zingen'),
(57, 'danstechniek', 'date', 'K/DP/10', 'Beroepsgerichte profielen DP', 'beroepsgericht keuzevak', 'danstechniek', 'danstechniek'),
(58, 'informatie, creatie en presentatie', 'icpr', 'ZW/icp', 'Beroepsgerichte profielen DP', 'beroepsgericht keuzevak', 'info creatie presentatie', 'informatie, creatie en presentatie'),
(59, 'economie en ondernemen', 'eo', 'eo', 'Beroepsgerichte profielen EO', 'profielvak', 'eco&ondern', 'economie en ondernemen'),
(60, 'retail & styling', 're&s', 'EO/rs', 'Beroepsgerichte profielen EO', 'profielmodule', 'retail & styling', 'retail & styling'),
(61, 'service & sales', 'se&s', 'EO/ses', 'Beroepsgerichte profielen EO', 'profielmodule', 'service & sales', 'service & sales'),
(62, 'stock & supplies', 'st&s', 'EO/sts', 'Beroepsgerichte profielen EO', 'profielmodule', 'stock & supplies', 'stock & supplies'),
(63, 'office & support', 'of&s', 'EO/os', 'Beroepsgerichte profielen EO', 'profielmodule', 'office & support', 'office & support'),
(64, 'administratie', 'adm', 'P/EO/04', 'Beroepsgerichte profielen (EO)', 'profielmodule', 'administratie', 'administratie'),
(65, 'commercieel', 'com', 'P/EO/01', 'Beroepsgerichte profielen (EO)', 'profielmodule', 'commercieel', 'commercieel'),
(66, 'logistiek', 'log', 'P/EO/03', 'Beroepsgerichte profielen (EO)', 'profielmodule', 'logistiek', 'logistiek'),
(67, 'secretarieel', 'sec', 'P/EO/02', 'Beroepsgerichte profielen (EO)', 'profielmodule', 'secretarieel', 'secretarieel'),
(68, 'distributie', 'dist', 'K/EO/03', 'Beroepsgerichte profielen EO', 'beroepsgericht keuzevak', 'distributie', 'distributie'),
(69, 'financieel en administratief beheer', 'fabh', 'K/EO/04', 'Beroepsgerichte profielen EO', 'beroepsgericht keuzevak', 'financieeladministratiefbeheer', 'financieel en administratief beheer'),
(70, 'financieel en administratief medewerker', NULL, 'EO/fam', 'Beroepsgerichte profielen EO', 'beroepsgericht keuzevak', NULL, NULL),
(71, 'internationale handel', 'ihan', 'K/EO/11', 'Beroepsgerichte profielen EO', 'beroepsgericht keuzevak', 'internationale handel', 'internationale handel'),
(72, 'marketing', 'mark', 'K/EO/01', 'Beroepsgerichte profielen EO', 'beroepsgericht keuzevak', 'marketing', 'marketing'),
(73, 'mode en design', 'mode', 'K/EO/08', 'Beroepsgerichte profielen EO', 'beroepsgericht keuzevak', 'modedesign', 'mode en design'),
(74, 'officemanagement', 'offm', 'K/EO/02', 'Beroepsgerichte profielen EO', 'beroepsgericht keuzevak', 'officemanagement', 'officemanagement'),
(75, 'ondernemen', 'ondn', 'K/EO/05', 'Beroepsgerichte profielen EO', 'beroepsgericht keuzevak', 'ondernemen', 'ondernemen'),
(76, 'presentatie en styling', 'prst', 'K/EO/07', 'Beroepsgerichte profielen EO', 'beroepsgericht keuzevak', 'presentatieenstyling', 'presentatie en styling'),
(77, 'webshop', 'webs', 'K/EO/06', 'Beroepsgerichte profielen EO', 'beroepsgericht keuzevak', 'webshop', 'webshop'),
(78, 'modetechniek', 'mote', 'K/EO/09', 'Beroepsgerichte profielen EO', 'beroepsgericht keuzevak', 'modetechniek', 'modetechniek'),
(79, 'wonen en design', 'wode', 'K/EO/10', 'Beroepsgerichte profielen EO', 'beroepsgericht keuzevak', 'wonen en design', 'wonen en design'),
(80, 'actief in de natuur', 'actn', 'K/GR/14', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'actiefindenatuur', 'actief in de natuur'),
(81, 'bloemwerk', 'blwk', 'K/GR/04/01', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'bloemwerk', 'bloemwerk'),
(82, 'duurzame melkveehouderij bedrijven en biodiversiteit vergroten', 'dmbv', 'K/GR/16', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'duurz melkv biod vergroten', 'duurzame melkveehouderij bedrijven en biodiversiteit vergroten'),
(83, 'paard en welzijn', 'paw', 'GR/pw', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'paard welzijn', 'paard en welzijn'),
(84, 'gezonde dieren', 'gzdr', 'K/GR/09', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'gezonddier', 'gezonde dieren'),
(85, 'groei en oogst', 'greo', 'K/GR/07', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'groeioogst', 'groei en oogst'),
(86, 'groei voorbereiden', 'grvb', 'K/GR/06', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'groeivoorbereiden', 'groei voorbereiden'),
(87, 'groen', 'grn', 'gr', 'Beroepsgerichte profielen Gr', 'profielvak', 'groen', 'groen'),
(88, 'groene productie', 'grpr', 'P/GR/01', 'Beroepsgerichte profielen Gr', 'profielmodule', 'groeneproductie', 'groene productie'),
(89, 'groene vormgeving en styling', 'grvs', 'K/GR/05', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'grvormstyling', 'groene vormgeving en styling'),
(90, 'groene vormgeving en verkoop', 'grvv', 'P/GR/04', 'Beroepsgerichte profielen Gr', 'profielmodule', 'grvormgverk', 'groene vormgeving en verkoop'),
(91, 'groene zorg', 'grzg', 'K/GR/12', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'groenezorg', 'groene zorg'),
(92, 'het groene machinepark', 'grmp', 'K/GR/01', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'groenmachinepark', 'het groene machinepark'),
(93, 'het houden van dieren', 'hvdr', 'K/GR/08', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'houdendier', 'het houden van dieren'),
(94, 'natuurlijk groen', 'natg', 'K/GR/13', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'natgroen', 'natuurlijk groen'),
(95, 'tuinontwerp en -aanleg', 'toa', 'K/GR/02', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'tuinontwaanl', 'tuinontwerp en -aanleg'),
(96, 'tussen productie en verkoop', 'tpv', 'P/GR/02', 'Beroepsgerichte profielen Gr', 'profielmodule', 'productverkoop', 'tussen productie en verkoop'),
(97, 'vergroening stedelijke omgeving', 'vgso', 'P/GR/03', 'Beroepsgerichte profielen Gr', 'profielmodule', 'vergroeningstedelijkeomgeving', 'vergroening stedelijke omgeving'),
(98, 'visstandbeheer en sportvisserij', 'viss', 'K/GR/15', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'visstandbeheer & sportvisserij', 'visstandbeheer en sportvisserij'),
(99, 'voeding: hoe maak je het?', 'voed', 'K/GR/11', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'voedinghoemaakjehet', 'voeding: hoe maak je het?'),
(100, 'water', 'watr', 'K/GR/10', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'water', 'water'),
(101, 'werk in tuin en landschap', 'wtl', 'K/GR/03', 'Beroepsgerichte profielen Gr', 'beroepsgericht keuzevak', 'werktuinland', 'werk in tuin en landschap'),
(102, 'horeca, bakkerij en recreatie', 'hbr', 'hbr', 'Beroepsgerichte profielen HBR', 'profielvak', 'horeca,bakk,recr', 'horeca, bakkerij en recreatie'),
(103, 'gastheerschap', 'ghs', 'P/HBR/01', 'Beroepsgerichte profielen HBR', 'profielmodule', 'gastheerschap', 'gastheerschap'),
(104, 'keuken', 'keu', 'P/HB R/03', 'Beroepsgerichte profielen HBR', 'profielmodule', 'keuken', 'de keuken'),
(105, 'bakkerij', 'bakk', 'P/HBR/02', 'Beroepsgerichte profielen HBR', 'profielmodule', 'bakkerij', 'de bakkerij'),
(106, 'recreatie', 'rec', 'P/HBR/04', 'Beroepsgerichte profielen HBR', 'profielmodule', 'recreatie', 'recreatie'),
(107, 'brood- en banketspecialisatie', 'bbsp', 'K/HBR/02', 'Beroepsgerichte profielen HBR', 'beroepsgericht keuzevak', 'broodenbanketspecialisatie', 'brood- en banketspecialisatie'),
(108, 'banketbakken 2', NULL, 'HBR/ban2', 'Beroepsgerichte profielen HBR', 'beroepsgericht keuzevak', NULL, NULL),
(109, 'broodbakken 2', NULL, 'HBR/brd2', 'Beroepsgerichte profielen HBR', 'beroepsgericht keuzevak', NULL, NULL),
(110, 'de bijzondere keuken', 'bzkk', 'K/HBR/06', 'Beroepsgerichte profielen HBR', 'beroepsgericht keuzevak', 'bijzkeuken', 'de bijzondere keuken'),
(111, 'evenementen', 'evem', 'K/HBR/04', 'Beroepsgerichte profielen HBR', 'beroepsgericht keuzevak', 'evenementen', 'evenementen'),
(112, 'facilitaire dienstverlening, beheer en onderhoud', 'fdbo', 'K/HBR/08', 'Beroepsgerichte profielen HBR', 'beroepsgericht keuzevak', 'facdienstverlbeheeronderhoud', 'facilitaire dienstverlening, beheer en onderhoud'),
(113, 'gastheerspecialisatie', 'ghsp', 'K/HBR/01', 'Beroepsgerichte profielen HBR', 'beroepsgericht keuzevak', 'gastheerspecialisatie', 'gastheerspecialisatie'),
(114, 'keukenspecialisatie', 'kksp', 'K/HBR/03', 'Beroepsgerichte profielen HBR', 'beroepsgericht keuzevak', 'keukenspecialisatie', 'keukenspecialisatie'),
(115, 'patisserie', 'pati', 'K/HBR/05', 'Beroepsgerichte profielen HBR', 'beroepsgericht keuzevak', 'patisserie', 'patisserie'),
(116, 'siervakken', 'srvk', 'K/HBR/09', 'Beroepsgerichte profielen HBR', 'beroepsgericht keuzevak', 'siervakken', 'siervakken'),
(117, 'traiteur', 'trai', 'K/HBR/07', 'Beroepsgerichte profielen HBR', 'beroepsgericht keuzevak', 'traiteur', 'traiteur'),
(118, 'maritiem en techniek', 'mate', 'mat', 'Beroepsgerichte profielen MaT', 'profielvak', 'maritiemtechn', 'maritiem en techniek'),
(119, 'maritieme logistiek en communicatie', 'mlc', 'P/MT/01', 'Beroepsgerichte profielen MaT', 'profielmodule', 'marlogcom', 'maritieme logistiek en communicatie'),
(120, 'maritieme veiligheid', 'mvh', 'P/MT02', 'Beroepsgerichte profielen MaT', 'profielmodule', 'marveiligh', 'maritieme veiligheid'),
(121, 'maritieme installaties', 'misl', 'P/MT/03', 'Beroepsgerichte profielen MaT', 'profielmodule', 'marinstall', 'maritieme installaties'),
(122, 'reparatie en onderhoud', 'repo', 'P/MT/04', 'Beroepsgerichte profielen MaT', 'profielmodule', 'reponderh', 'reparatie en onderhoud'),
(123, 'cargadoor', 'carg', 'K/MT/11', 'Beroepsgerichte profielen MaT', 'beroepsgericht keuzevak', 'cargadoor', 'cargadoor'),
(124, 'commerciële visserij', 'cvis', 'MT/comv', 'Beroepsgerichte profielen MaT', 'beroepsgericht keuzevak', 'commerciële visserij', 'commerciële visserij'),
(125, 'conserveren van maritieme systemen', 'cvms', 'K/MT/15', 'Beroepsgerichte profielen MaT', 'beroepsgericht keuzevak', 'conserverenmaritiemesystemen', 'conserveren van maritieme systemen'),
(126, 'dienstverlening in de haven', 'dvlh', 'K/MT/06', 'Beroepsgerichte profielen MaT', 'beroepsgericht keuzevak', 'dienstverleninghaven', 'dienstverlening in de haven'),
(127, 'expediteur, luchtvaart en douane', 'elvd', 'K/MT/10', 'Beroepsgerichte profielen MaT', 'beroepsgericht keuzevak', 'expediteurluchtvdouane', 'expediteur, luchtvaart en douane'),
(128, 'ladingadministratie in de haven', 'lahv', 'K/MT/09', 'Beroepsgerichte profielen MaT', 'beroepsgericht keuzevak', 'ladingadministrhaven', 'ladingadministratie in de haven'),
(129, 'ladingbehandeling aan boord', 'lbhb', 'K/MT/02', 'Beroepsgerichte profielen MaT', 'beroepsgericht keuzevak', 'ladingbehandelingboord', 'ladingbehandeling aan boord'),
(130, 'maritieme mechanische installaties', 'mmis', 'K/MT/14/KT', 'Beroepsgerichte profielen MaT', 'beroepsgericht keuzevak', 'maritiememechinstall', 'maritieme mechanische installaties'),
(131, 'nautische materialen en gereedschappen', 'nmgs', 'K/MT/12', 'Beroepsgerichte profielen MaT', 'beroepsgericht keuzevak', 'nautischematgereedsch', 'nautische materialen en gereedschappen'),
(132, 'navigatie', 'navi', 'K/MT/03', 'Beroepsgerichte profielen MaT', 'beroepsgericht keuzevak', 'navigatie', 'navigatie'),
(133, 'opslag en overslag in de haven', 'oeoh', 'K/MT/07', 'Beroepsgerichte profielen MaT', 'beroepsgericht keuzevak', 'opslagoverslaghaven', 'opslag en overslag in de haven'),
(134, 'scheepsconstructie en -ontwerp', 'scow', 'K/MT/13', 'Beroepsgerichte profielen MaT', 'beroepsgericht keuzevak', 'scheepsconstrontwerp', 'scheepsconstructie en -ontwerp'),
(135, 'scheepskennis', 'scke', 'K/MT/04', 'Beroepsgerichte profielen MaT', 'beroepsgericht keuzevak', 'scheepskennis', 'scheepskennis'),
(136, 'stuwadoor en vorkheftruck', 'stvh', 'K/MT/08', 'Beroepsgerichte profielen MaT', 'beroepsgericht keuzevak', 'stuwadoorenvorkheftruck', 'stuwadoor en vorkheftruck'),
(137, 'werken en leven aan boord', 'wlab', 'K/MT/01', 'Beroepsgerichte profielen MaT', 'beroepsgericht keuzevak', 'werklevenab', 'werken en leven aan boord'),
(138, 'zeevaartkunde', 'zvku', 'K/MT/05', 'Beroepsgerichte profielen MaT', 'beroepsgericht keuzevak', 'zeevaartkunde', 'zeevaartkunde'),
(139, 'haven en vervoer', 'hvs', 'K/MT/09/02', 'Beroepsgerichte profielen MaT', 'vak met individuele licentie', 'havenvervoer', 'haven en vervoer'),
(140, 'rijn, binnen- en kustvaart', 'rbk', 'K/MT/rijnbkv', 'Beroepsgerichte profielen MaT', 'vak met individuele licentie', 'rbkvaart', 'rijn, binnen- en kustvaart'),
(141, 'mobiliteit en transport', 'mobt', 'mt', 'Beroepsgerichte profielen MT', 'profielvak', 'mobiliteittransport', 'mobiliteit en transport'),
(142, 'motorconditie testen', 'mct', 'P/MET/01', 'Beroepsgerichte profielen MT', 'profielmodule', 'motorconditietest', 'motorconditie testen'),
(143, 'wielophanging en carrosserie', 'wohc', 'P/MET/02', 'Beroepsgerichte profielen MT', 'profielmodule', 'wielophcarrosserie', 'wielophanging en carrosserie'),
(144, 'verlichtings- en comfortsystemen', 'vlcs', 'P/MET/03', 'Beroepsgerichte profielen MT', 'profielmodule', 'verlichtcomfortsyst', 'verlichtings- en comfortsystemen'),
(145, 'transport', 'trns', 'P/MET/04', 'Beroepsgerichte profielen MT', 'profielmodule', 'transport', 'transport'),
(146, 'aandrijf- en remsystemen', 'adrs', 'K/MET/06', 'Beroepsgerichte profielen MT', 'beroepsgericht keuzevak', 'aandrijfremsyst', 'aandrijf- en remsysteem'),
(147, 'autoschade en spuiten', 'ass', 'P/MVI/01', 'Beroepsgerichte profielen MT', 'beroepsgericht keuzevak', 'autoschadespuiten', 'autoschade en spuiten'),
(148, 'bedrijfswagens', 'bdrw', 'K/MET/04', 'Beroepsgerichte profielen MT', 'beroepsgericht keuzevak', 'bedrijfswag', 'bedrijfswagens'),
(149, 'carrosseriebouw', 'carb', 'K/MET/07', 'Beroepsgerichte profielen MT', 'beroepsgericht keuzevak', 'carrosseriebouw', 'carrosseriebouw'),
(150, 'electrische voertuigen', 'elvt', 'K/MET/13', 'Beroepsgerichte profielen MT', 'beroepsgericht keuzevak', 'elektrischevoert', 'elektrische voertuigen'),
(151, 'elektronica', 'elek', 'K/MET/03', 'Beroepsgerichte profielen MT', 'beroepsgericht keuzevak', 'elektronica', 'elektronica'),
(152, 'fietstechniek', 'ftst', 'K/MET/05', 'Beroepsgerichte profielen MT', 'beroepsgericht keuzevak', 'fietstechn', 'fietstechniek'),
(153, 'fietstechniek 2', NULL, 'MT/ff2', 'Beroepsgerichte profielen MT', NULL, NULL, NULL),
(154, 'gemotoriseerde tweewieler', 'mott', 'K/MET/06', 'Beroepsgerichte profielen MT', 'beroepsgericht keuzevak', 'gemottweewiel', 'gemotoriseerde tweewieler'),
(155, 'gemotoriseerde tweewieler 2', NULL, 'MT/gm2', 'Beroepsgerichte profielen MT', NULL, NULL, NULL),
(156, 'mobiele werktuigen', 'mwt', 'K/MET/11', 'Beroepsgerichte profielen MT', 'beroepsgericht keuzevak', 'mobwerktuigen', 'mobiele werktuigen'),
(157, 'motorsystemen', 'mots', 'K/MET/01', 'Beroepsgerichte profielen MT', 'beroepsgericht keuzevak', 'motorsyst', 'motorsystemen'),
(158, 'operationele magazijnwerkzaamheden', 'omwz', 'K/MET/12', 'Beroepsgerichte profielen MT', 'beroepsgericht keuzevak', 'operatmagzwerkz', 'operationele magazijnwerkzaamheden'),
(159, 'ritvoorbereiding en ritafhandeling', 'rvra', 'K/MET/10', 'Beroepsgerichte profielen MT', 'beroepsgericht keuzevak', 'ritvoorb/afhand', 'ritvoorbereiding en ritafhandeling'),
(160, 'verbrandingsmotoren', 'vbrm', 'K/MET/09', 'Beroepsgerichte profielen MT', 'beroepsgericht keuzevak', 'verbrandingsmot', 'verbrandingsmotoren'),
(161, 'media, vormgeving en ICT', 'mvic', 'mvi', 'Beroepsgerichte profielen MVI', 'profielvak', 'mediavorgICT', 'media, vormgeving en ICT'),
(162, 'audiovisuele vormgeving en productie', 'avp', 'P/MVI/01', 'Beroepsgerichte profielen MVI', 'profielmodule', 'audiovisvormgprod', 'audiovisuele vormgeving en productie'),
(163, '2D- en 3D-vormgeving en -productie', '2d3d', 'P/MVI/02', 'Beroepsgerichte profielen MVI', 'profielmodule', '2D/3Dvormgprod', '2D- en 3D-vormgeving en -productie'),
(164, 'ICT', 'ict', 'P/MVI/03', 'Beroepsgerichte profielen MVI', 'profielmodule', 'ict', 'ICT'),
(165, 'interactieve vormgeving en productie', 'ivp', 'P/MVI/04', 'Beroepsgerichte profielen MVI', 'profielmodule', 'interactvormgprod', 'interactieve vormgeving en productie'),
(166, '3D-vormgeving en - realisatie', '3dvr', 'K/MVI/01', 'Beroepsgerichte profielen MVI', 'beroepsgericht keuzevak', '3Dvormreal', '3D-vormgeving en -realisatie'),
(167, 'applicatieontwikkeling', 'appo', 'K/MVI/09', 'Beroepsgerichte profielen MVI', 'beroepsgericht keuzevak', 'appl-ontwikkeling', 'applicatieontwikkeling'),
(168, 'digitale beveiliging', 'dgbv', 'K/MV/10', 'Beroepsgerichte profielen MVI', 'beroepsgericht keuzevak', 'digibeveiliging', 'digitale beveiliging'),
(169, 'fotografie', 'foto', 'K/MVI/07', 'Beroepsgerichte profielen MVI', 'beroepsgericht keuzevak', 'fotograf', 'fotografie'),
(170, 'game-design', 'gamd', 'K/mvi/06', 'Beroepsgerichte profielen MVI', 'beroepsgericht keuzevak', 'game-design', 'game-design'),
(171, 'idee-ontwikkeling', 'idee', 'K/MVI/02', 'Beroepsgerichte profielen MVI', 'beroepsgericht keuzevak', 'ideeontw', 'idee-ontwikkeling'),
(172, 'innovatie en prototyping', 'inpt', 'K/MVI/03', 'Beroepsgerichte profielen MVI', 'beroepsgericht keuzevak', 'innovatie en prototyping', 'innovatie en prototyping'),
(173, 'licht, geluid en decor', 'lgd', 'K/MVI/08', 'Beroepsgerichte profielen MVI', 'beroepsgericht keuzevak', 'licht,geluid,dec', 'licht, geluid en decor'),
(174, 'netwerkbeheer', 'netw', 'K/MVI/03', 'Beroepsgerichte profielen MVI', 'beroepsgericht keuzevak', 'netwerkbeh', 'netwerkbeheer'),
(175, 'printmediaproductie', 'pmp', 'K/MVI/04', 'Beroepsgerichte profielen MVI', 'beroepsgericht keuzevak', 'printmediaprod', 'printmediaproductie'),
(176, 'sign', 'sign', 'K/MVI/11', 'Beroepsgerichte profielen MVI', 'beroepsgericht keuzevak', 'sign', 'sign'),
(177, 'tekenen, schilderen en illustreren', 'tsi', 'K/MVI/05', 'Beroepsgerichte profielen MVI', 'beroepsgericht keuzevak', 'tekschildillustr', 'tekenen, schilderen en illustreren'),
(178, 'vormgeven en typografie', 'vgtg', 'K/MVI/12', 'Beroepsgerichte profielen MVI', 'beroepsgericht keuzevak', 'vormgtypogr', 'vormgeven & typografie'),
(179, 'produceren, installeren en energie', 'stec', 'pie', 'Beroepsgerichte profielen PIE', 'profielvak', 'slimme technologie', 'produceren, installeren en energie'),
(180, 'ontwerpen en maken', 'ontw', 'P/PIE/01', 'Beroepsgerichte profielen PIE', 'profielmodule', 'ontwerpenmaken', 'ontwerpen en maken'),
(181, 'bewerken en verbinden van materialen', 'bevm', 'P/PIE/02', 'Beroepsgerichte profielen PIE', 'profielmodule', 'bewerkverbmat', 'bewerken en verbinden van materialen'),
(182, 'besturen en automatiseren', 'baut', 'P/PIE/03', 'Beroepsgerichte profielen PIE', 'profielmodule', 'bestautom', 'besturen en automatiseren'),
(183, 'installeren en monteren', 'insm', 'P/PIE/04', 'Beroepsgerichte profielen PIE', 'profielmodule', 'installmont', 'installeren en monteren'),
(184, 'booglasprocessen', 'bglp', 'K/PIE/02', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'booglasprocessen', 'booglasprocessen'),
(185, 'cloud en cybersecurity', 'clcy', 'K/PIE/18', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'cloud & cybersecurity', 'cloud en cybersecurity'),
(186, 'CNC-technieken', 'cnc', 'K/PIE/09', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'CNCtechn', 'CNC-technieken'),
(187, 'dakbedekking', 'dakb', 'K/PIE/11', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'dakbedekk', 'dakbedekking'),
(188, 'domotica en automatisering', 'dmat', 'K/PIE/14', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'domoticaautomatisering', 'domotica en automatisering'),
(189, 'drinkwater en sanitair', 'drws', 'K/PIE/10', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'drinkwatersanitair', 'drinkwater en sanitair'),
(190, 'dronetechniek I: vliegen met een drone in beroepssituaties', 'dt1', 'K/PIE/22', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'dronetechniek I', 'dronetechniek I'),
(191, 'dronetechniek II:  inspecteren met behulp van drones', 'dt2', 'K/PIE/23', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'dronetechniek II', 'dronetechniek II'),
(192, 'duurzame energie', 'drze', 'K/PIE/05', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'duurzameenergie', 'duurzame energie'),
(193, 'edelmetaal bewerken', 'edel', 'K/PIE/24', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'edelmetaal bewerken', 'edelmetaal bewerken'),
(194, 'klimaattechnologie', 'klit', 'K/PIE/03', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'klimaattechn', 'klimaattechnologie'),
(195, 'koudetechniek', 'koud', 'K/PIE/16', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'koudetechniek', 'koudetechniek'),
(196, 'lasrobot', 'lrbt', 'K/PIE/19', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'lasrobot', 'lasrobot'),
(197, 'licht, geluid en beeld', 'lglb', 'K/PIE/17', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'lichtgeluidbeeld', 'licht, geluid en beeld'),
(198, 'machinebouw en verspanen', 'mbvs', 'K/PIE/20', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'machinebouwverspanen', 'machinebouw – verspanen'),
(199, 'nutsvoorzieningen', 'nvz', 'K/PIE/15', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'nutsvoorz', 'nutsvoorzieningen'),
(200, 'ontwerp duurzame comfortwoning', 'docw', 'K/BWI/20', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'ontwduurzcomfortwoning', 'ontwerp duurzame comfortwoning'),
(201, 'plaat- en constructiewerk', 'plcw', 'K/PIE/01', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'plaatconstrwerk', 'plaat- en constructiewerk'),
(202, 'praktisch booglassen', 'prbl', 'K/PIE/08', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'praktisch booglassen', 'praktisch booglassen'),
(203, 'procestechniek', 'pt', 'K/PIE/04', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'procestechn', 'procestechniek'),
(204, 'slimme technologie', 'stec', 'K/PIE/21', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'slimme technologie', 'slimme technologie'),
(205, 'utiliteitsinstallaties', 'utii', 'K/PIE/07', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'utiliteitsinstal', 'utiliteitsinstallaties'),
(206, 'verspaningstechnieken', 'vspt', 'K/PIE/12', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'verspaningstechn', 'verspaningstechnieken'),
(207, 'water, techniek en duurzaamheid', 'wt&d', 'K/PIE/25', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'water, techniek&duurzaamheid', 'water, techniek en duurzaamheid'),
(208, 'composiet', 'cmp', 'PIE/com', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'composiet', 'composiet'),
(209, 'werktuigkundig en elektrotechnisch onderhoud', 'wtet', 'K/PIO/06', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'wtkelektrotonderh', 'werktuigkundig en elektrotechnisch onderhoud'),
(210, 'woon- en kantoortechnologie', 'wkt', 'K/PII/13', 'Beroepsgerichte profielen PIE', 'beroepsgericht keuzevak', 'woonkantoortechn', 'woon- en kantoortechnologie'),
(211, 'zorg en welzijn', 'zw', 'zw', 'Beroepsgerichte profielen ZW', 'profielvak', 'zorgwelzijn', 'zorg en welzijn'),
(212, 'mens en gezondheid', 'mgez', 'P/ZW/01', 'Beroepsgerichte profielen ZW', 'profielmodule', 'mensgezondh', 'mens en gezondheid'),
(213, 'mens en omgeving', 'momg', 'P/ZW/02', 'Beroepsgerichte profielen ZW', 'profielmodule', 'mensomgev', 'mens en omgeving'),
(214, 'mens en activiteit', 'mact', 'P/ZW/03', 'Beroepsgerichte profielen ZW', 'profielmodule', 'mensactivit', 'mens en activiteit'),
(215, 'mens en zorg', 'mzrg', 'P/ZW/04', 'Beroepsgerichte profielen ZW', 'profielmodule', 'menszorg', 'mens en zorg'),
(216, 'assisteren in de gezondheidszorg', 'aghz', 'K/ZW/07', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'assisteren id gezondheidszorg', 'assisteren in de gezondheidszorg'),
(217, 'beveiliging en veiligheid', 'bevv', 'K/ZW/10', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'beveilig/veiligh', 'beveiliging en veiligheid'),
(218, 'congiërgewerkzaamheden', 'cgwz', 'ZW/cw', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'conciërgewerkzaamheden', 'conciërgewerkzaamheden'),
(219, 'dagbesteding', 'dagb', 'K/ZW/08/02', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'dagbesteding', 'dagbesteding'),
(220, 'facilitaire dienstverlening, catering en inrichting', 'fdci', 'K/ZW/09', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'facd: catering en inrichting', 'facilitaire dienstverlening: catering en inrichting'),
(221, 'facilitaire dienstverlening, inrichting en verzorging', 'fdiv', 'ZW/fdiv', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'facdverlinrichtingverzorging', 'facilitaire dienstverlening: inrichting en verzorging'),
(222, 'facilitaire dienstverlening, onderhoud en receptie', 'fdor', 'K/ZW/10', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'facd: onderhoud en receptie', 'facilitaire dienstverlening: onderhoud en receptie'),
(223, 'haarverzorging', 'hrvz', 'K/ZW/02', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'haarverzorg', 'haarverzorging'),
(224, 'hand- en voetverzorging', 'hvvz', 'K/ZW/04', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'hand/voetverz', 'hand- en voetverzorging'),
(225, 'huidverzorging', 'hdvz', 'K/ZW/03', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'huidverzorg', 'huidverzorging'),
(226, 'kennismaking met uiterlijke verzorging', 'kmuv', 'K/ZW/01', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'kennism uiterlijke verzorging', 'kennismaking met uiterlijke verzorging'),
(227, 'ondersteuning bij sport- en bewegingsactiviteiten', 'osba', 'K/ZW/01', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'onderst sport- en bewegingsact', 'ondersteuning bij sport- en bewegingsactiviteiten'),
(228, 'schoonheidsbehandeling hand, haar en gezicht', 'shhg', 'ZW/shhg', 'Beroepsgerichte profielen (ZW)', 'beroepsgericht keuzevak', 'schoonheidsbehhandhaargezicht', 'schoonheidsbehandeling hand, haar en gezicht'),
(229, 'sport en bewegen', 'spbw', 'K/ZW/12', 'Beroepsgerichte profielen (ZW)', 'beroepsgericht keuzevak', 'sportbewegen', 'sport en bewegen'),
(230, 'technologie binnen zorg en welzijn', 'tbzw', 'K/ZW/13', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'techn zorg en welzijn', 'technologie binnen zorg en welzijn'),
(231, 'verzorging', 'verz', 'ZW/vz', 'Beroepsgerichte profielen (ZW)', 'beroepsgericht keuzevak', 'verzorging', 'verzorging'),
(232, 'voorkomen van ongevallen en EHBO', 'ehbo', 'K/ZW/12', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'ongevallenehbo', 'voorkomen van ongevallen en EHBO'),
(233, 'welzijn kind en jongere', 'wzkj', 'K/ZW/05', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'welzijnkindenjongere', 'welzijn kind en jongere'),
(234, 'welzijn volwassenen en ouderen', 'wzvo', 'K/ZW/08', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'welzijn volwassenen en ouderen', 'welzijn volwassenen en ouderen'),
(235, 'wonen en huishouden', 'whh', 'K/ZW/06', 'Beroepsgerichte profielen ZW', 'beroepsgericht keuzevak', 'wonenhuish', 'wonen en huishouden'),
(236, 'bouwen, wonen, interieur / produceren, installeren en energie', 'bwpi', 'BWI/PIE', 'Beroepsgerichte profielen BWI/PIE', 'profielvak', 'bwi_pie', 'bouwen, wonen, interieur / produceren, installeren en energie'),
(237, 'bouwen, wonen, interieur / produceren, installeren en energie / mobiliteit en transport', 'bwpm', 'BWI/PIE/MT', 'Beroepsgerichte profielen BWI/PIE/MT', 'profielvak', 'bwi_pie_mtr', 'bouwen, wonen, interieur / produceren, installeren en energie / mobiliteit en transport'),
(238, 'horeca, bakkerij en recreatie / zorg en welzijn', 'hbzw', 'HBR/ZW', 'Beroepsgerichte profielen HBR/ZW', 'profielvak', 'hbr_zw', 'horeca, bakkerij en recreatie / zorg en welzijn'),
(239, 'zorg en welzijn / economie en ondernemen', 'zweo', 'ZW/EO', 'Beroepsgerichte profielen ZW/EO', 'profielvak', 'zw_eo', 'zorg en welzijn / economie en ondernemen'),
(240, 'bewegen en sport', NULL, 'bs', 'Bewegen en sport', NULL, NULL, NULL),
(241, 'bewegen, sport en maatschappij', 'bsm', 'bsw', 'Bewegen en sport', NULL, 'bsm', 'bewegen, sport en maatschappij'),
(242, 'lichamelijke opvoeding', 'lo', 'lo', 'Bewegen en sport', NULL, 'lo', 'lichamelijke opvoeding'),
(243, 'lichamelijke opvoeding II', 'lo2', 'lo2', 'Bewegen en sport', NULL, 'lo2', 'lichamelijke opvoeding 2'),
(244, 'burgerschap', NULL, 'bu', 'Burgerschap', NULL, NULL, NULL),
(245, 'digitale geletterdheid', NULL, 'DG', 'Digitale geletterdheid', NULL, NULL, NULL),
(246, 'digitale veiligheid', NULL, 'DG/dv', 'Digitale geletterdheid', NULL, NULL, NULL),
(247, 'informatica', 'in', 'inf', 'Digitale geletterdheid', NULL, 'Informatica', 'informatica'),
(248, 'informatiekunde', NULL, 'DG/inf', 'Digitale geletterdheid', NULL, NULL, NULL),
(249, 'Grieks', 'gtc', 'gtc', 'Klassieke talen', NULL, 'Griekse tc', 'Griekse taal en cultuur'),
(250, 'Latijn', 'ltc', 'ltc', 'Klassieke talen', NULL, 'Latijnse tc', 'Latijnse taal en cultuur'),
(251, 'Hebreeuws (klassiek)', 'khtl', 'MVT/heb', 'Klassieke talen', NULL, 'klassiek hebreeuwse tali', 'klassiek Hebreeuwse taal en literatuur'),
(252, 'audiovisuele vormgeving', 'bav', 'P/MVI/01', 'Kunst en cultuur', NULL, 'beeldend-av', 'beeldende vakken – audiovisuele vorming'),
(253, 'beeldend', 'kubv', 'bv', 'Kunst en cultuur', NULL, 'kunst beeldend', 'kunst (beeldende vormgeving)'),
(254, 'ckv', 'ckv', 'ckv', 'Kunst en cultuur', NULL, 'ckv', 'culturele en kunstzinnige vorming'),
(255, 'kunstvakken incl. ckv', 'kckv', 'kv1', 'Kunst en cultuur', NULL, 'kunstvakken incl ckv', 'kunstvakken inclusief ckv'),
(256, 'kunst en cultuur', NULL, 'kc', 'Kunst en cultuur', NULL, NULL, NULL),
(257, 'kunst', 'kua', 'kua', 'Kunst en cultuur', NULL, 'kunst algemeen', 'kunst (algemeen)'),
(258, 'cultureel erfgoed', NULL, 'ce', 'Kunst en cultuur', NULL, NULL, NULL),
(259, 'klassieke culturele vorming', 'kcv', 'kcv', 'Kunst en cultuur', NULL, 'kcv', 'klassieke culturele vorming'),
(260, 'culturele orientatie en creatieve expressie', NULL, 'coce', 'Kunst en cultuur', NULL, NULL, NULL),
(261, 'dans', 'kda', 'da', 'Kunst en cultuur', NULL, 'dans', 'dans'),
(262, 'kunst (dans)', 'kuda', 'kuda', 'Kunst en cultuur', NULL, 'kunst dans', 'kunst (dans)'),
(263, 'drama', 'kdr', 'dr', 'Kunst en cultuur', NULL, 'drama', 'drama'),
(264, 'kunst (drama)', 'kudr', 'kudr', 'Kunst en cultuur', NULL, 'kunst drama', 'kunst (drama)'),
(265, 'film', 'bfi', 'P/DP/04/02', 'Kunst en cultuur', NULL, 'beeldend-fi', 'beeldende vakken – film'),
(266, 'fotografie', 'bfo', 'KC/fot', 'Kunst en cultuur', NULL, 'beeldend-fo', 'beeldende vakken – fotografie'),
(267, 'handvaardigheid', 'hndv', 'THTex', 'Kunst en cultuur', NULL, 'handvaardigheid', 'handvaardigheid'),
(268, 'muziek', 'mu', 'muz', 'Kunst en cultuur', NULL, 'muziek', 'muziek'),
(269, 'tekenen', 'te', 'thtex', 'Kunst en cultuur', NULL, 'tekenen', 'tekenen'),
(270, 'textiele werkvormen', 'txvg', 'KC/tw', 'Kunst en cultuur', NULL, 'textiele vorm', 'textiele vormgeving'),
(271, 'theater', NULL, 'KC/thea', 'Kunst en cultuur', NULL, NULL, NULL),
(272, 'aardrijkskunde', 'ak', 'ak', 'Mens en maatschappij', NULL, 'aardrijkskunde', 'aardrijkskunde'),
(273, 'bedrijfseconomie', 'beco', 'be', 'Mens en maatschappij', NULL, 'bedrijfseconomie', 'bedrijfseconomie'),
(274, 'economie', 'econ', 'ec', 'Mens en maatschappij', NULL, 'economie', 'economie'),
(275, 'filosofie', 'fi', 'fi', 'Mens en maatschappij', NULL, 'filosofie', 'filosofie'),
(276, 'geschiedenis', 'ges', 'gs', 'Mens en maatschappij', NULL, 'geschiedenis', 'geschiedenis'),
(277, 'geschiedenis en staatsinrichting', 'gs', 'GS/vmbo', 'Mens en maatschappij', NULL, 'gesch/staatsinr', 'geschiedenis en staatsinrichting'),
(278, 'godsdienst en/of levensbeschouwing', 'gds', 'MM/gl', 'Mens en maatschappij', NULL, 'godsdienst', 'godsdienst'),
(279, 'maatschappijkunde', 'mask', 'mk', 'Mens en maatschappij', NULL, 'maatschappijkunde', 'maatschappijkunde'),
(280, 'maatschappijleer', 'maat', 'mi', 'Mens en maatschappij', NULL, 'mijleer', 'maatschappijleer'),
(281, 'maatschappijleer II', 'ma2', 'MM/mijII', 'Mens en maatschappij', NULL, 'mijleer II', 'maatschappijleer II'),
(282, 'maatschappijwetenschappen', 'maw', 'maw', 'Mens en maatschappij', NULL, 'maatschwet', 'maatschappijwetenschappen'),
(283, 'management en organisatie', NULL, 'mo', 'Mens en maatschappij', NULL, NULL, NULL),
(284, 'mens en maatschappij', NULL, 'mm', 'Mens en maatschappij', NULL, NULL, NULL),
(285, 'staatsinrichting', NULL, 'PO/staats', 'Mens en maatschappij', NULL, NULL, NULL),
(286, 'verkeer', NULL, 'PO/verk', 'Mens en maatschappij', NULL, NULL, NULL),
(287, 'maatschappelijke stage', 'msst', 'MM/ms', 'Mens en maatschappij', NULL, 'maatsch stage', 'maatschappelijke stage'),
(288, 'algemene natuurwetenschappen', 'anw', 'anw', 'Mens en natuur', NULL, 'anw', 'algemene natuurwetenschappen'),
(289, 'biologie', 'biol', 'bio', 'Mens en natuur', NULL, 'biologie', 'biologie'),
(290, 'mens en natuur', NULL, 'mn', 'Mens en natuur', NULL, NULL, NULL),
(291, 'natuur en milieueducatie', NULL, 'PO/nem', 'Mens en natuur', NULL, NULL, NULL),
(292, 'natuur- en scheikunde I', 'nsk1', 'nask1', 'Mens en natuur', NULL, 'nask I', 'natuur- en scheikunde I'),
(293, 'natuur- en scheikunde II', 'nsk2', 'nask2', 'Mens en natuur', NULL, 'nask II', 'natuur- en scheikunde II'),
(294, 'natuur, leven en technologie', 'nlt', 'nlt', 'Mens en natuur', NULL, 'nlt', 'natuur, leven en technologie'),
(295, 'natuurkunde', 'nat', 'na', 'Mens en natuur', NULL, 'natuurkunde', 'natuurkunde'),
(296, 'scheikunde', 'schk', 'sk', 'Mens en natuur', NULL, 'scheikunde', 'scheikunde'),
(297, 'techniek', NULL, 'tech', 'Mens en natuur', NULL, NULL, NULL),
(298, 'onderzoeken en ontwerpen', 'o&o', 'MN/oo', 'Mens en natuur', NULL, 'o&o', 'onderzoek en ontwerpen'),
(299, 'Arabisch', 'artl', 'ar', 'Moderne vreemde talen', NULL, 'Arabisch', 'Arabische taal en literatuur'),
(300, 'Chinees', 'chtc', 'ch', 'Moderne vreemde talen', NULL, 'Chinees', 'Chinese taal en cultuur'),
(301, 'Duits', 'dutl', 'du', 'Moderne vreemde talen', NULL, 'Duits', 'Duitse taal en literatuur'),
(302, 'Engels', 'entl', 'en', 'Moderne vreemde talen', NULL, 'Engels', 'Engelse taal en literatuur'),
(303, 'Frans', 'fatl', 'fa', 'Moderne vreemde talen', NULL, 'Frans', 'Franse taal en literatuur'),
(304, 'Fries', 'frtc', 'fr', 'Moderne vreemde talen', NULL, 'Fries', 'Friese taal en cultuur'),
(305, 'Hebreeuws (modern)', 'mhtl', NULL, 'Moderne vreemde talen', NULL, 'modern hebreeuwse tali', 'modern Hebreeuwse taal en literatuur'),
(306, 'Italiaans', 'ittl', 'it', 'Moderne vreemde talen', NULL, 'Italiaans', 'Italiaanse taal en literatuur'),
(307, 'Papiaments', 'pap', 'MVT/pap', 'Moderne vreemde talen', NULL, 'Papiaments', 'Papiaments'),
(308, 'Portugees', 'port', 'MVT/port', 'Moderne vreemde talen', NULL, 'Portugees', 'Portugees'),
(309, 'Russisch', 'rutl', 'ru', 'Moderne vreemde talen', NULL, 'Russisch', 'Russische taal en literatuur'),
(310, 'Spaans', 'sptl', 'sp', 'Moderne vreemde talen', NULL, 'Spaans', 'Spaanse taal en literatuur'),
(311, 'Turks', 'tutl', 'tu', 'Moderne vreemde talen', NULL, 'Turks', 'Turkse taal en literatuur'),
(312, 'aanvankelijk lezen', NULL, 'PO/al', 'Nederlands', NULL, NULL, NULL),
(313, 'begrijpend lezen', NULL, 'PO/bl', 'Nederlands', NULL, NULL, NULL),
(314, 'lezen', NULL, 'PO/lz', 'Nederlands', NULL, NULL, NULL),
(315, 'literatuur', 'lit', 'c', 'Nederlands', NULL, 'literatuur', 'literatuur'),
(316, 'mondeling taalonderwijs', NULL, 'PO/mt', 'Nederlands', NULL, NULL, NULL),
(317, 'Nederlands', 'netl', 'ne', 'Nederlands', NULL, 'Nederlands', 'Nederlandse taal en literatuur'),
(318, 'Nederlands als tweede taal', NULL, 'PO/nt2', 'Nederlands', NULL, NULL, NULL),
(319, 'schrijven', NULL, 'PO/schr', 'Nederlands', NULL, NULL, NULL),
(320, 'spelling', NULL, 'PO/spe', 'Nederlands', NULL, NULL, NULL),
(321, 'taal', NULL, 'B', 'Nederlands', NULL, NULL, NULL),
(322, 'tekstbegrip', NULL, 'PO/tb', 'Nederlands', NULL, NULL, NULL),
(323, 'voorbereidend lezen', NULL, 'PO/vl', 'Nederlands', NULL, NULL, NULL),
(324, 'voortgezet technisch lezen', NULL, 'PO/vtl', 'Nederlands', NULL, NULL, NULL),
(325, 'woordenschat', NULL, 'PO/ws', 'Nederlands', NULL, NULL, NULL),
(326, 'bouwen, wonen en interieur', 'pvbw', 'PP/bwi', 'Praktijkgerichte programma''s', 'praktijkgericht vak', 'pv bouwen, wonen en interieur', 'praktijkgericht vak bouwen, wonen en interieur'),
(327, 'dienstverlening en producten', 'pvdp', 'PP/dp', 'Praktijkgerichte programma''s', 'praktijkgericht vak', 'pv dienstverlening en producte', 'praktijkgericht vak dienstverlening en producten'),
(328, 'economie en ondernemen', 'pveo', 'PP/eo', 'Praktijkgerichte programma''s', 'praktijkgericht vak', 'pv economie en ondernemen', 'praktijkgericht vak economie en ondernemen'),
(329, 'groen', 'pvgr', 'PP/gr', 'Praktijkgerichte programma''s', 'praktijkgericht vak', 'pv groen', 'praktijkgericht vak groen'),
(330, 'horeca, bakkerij en recreatie', 'pvhb', 'PP/hbr', 'Praktijkgerichte programma''s', 'praktijkgericht vak', 'pv horeca, bakkerij&recreatie', 'praktijkgericht vak horeca, bakkerij en recreatie'),
(331, 'informatietechnologie', 'pvit', 'it', 'Praktijkgerichte programma''s', 'praktijkgericht vak', 'pv informatietechnologie', 'praktijkgericht vak informatietechnologie'),
(332, 'maritiem en techniek', 'pvma', 'PP/mat', 'Praktijkgerichte programma''s', 'praktijkgericht vak', 'pv maritiem en techniek', 'praktijkgericht vak maritiem en techniek'),
(333, 'media, vormgeving en ict', 'pvmv', 'PP/mvi', 'Praktijkgerichte programma''s', 'praktijkgericht vak', 'pv media, vormgeving en ict', 'praktijkgericht vak media, vormgeving en ict'),
(334, 'mobiliteit en transport', 'pvmt', 'PP/mt', 'Praktijkgerichte programma''s', 'praktijkgericht vak', 'pv mobiliteit en transport', 'praktijkgericht vak mobiliteit en transport'),
(335, 'produceren, installeren en energie', 'pvpi', 'PP/pie', 'Praktijkgerichte programma''s', 'praktijkgericht vak', 'pv produceren, installeren&ene', 'praktijkgericht vak produceren, installeren en energie'),
(336, 'techniek en innovatief vakmanschap', 'pvti', 'PP/tiv', 'Praktijkgerichte programma''s', 'praktijkgericht vak', 'pv techniek&innovatief vakmans', 'praktijkgericht vak techniek en innovatief vakmanschap'),
(337, 'technologie en toepassing', 'pvtt', 'PP/tet', 'Praktijkgerichte programma''s', 'praktijkgericht vak', 'pv technologie en toepassing', 'praktijkgericht vak technologie en toepassing'),
(338, 'zorg en welzijn', 'pvzw', 'PP/zw', 'Praktijkgerichte programma''s', 'praktijkgericht vak', 'pv zorg en welzijn', 'praktijkgericht vak zorg en welzijn'),
(339, 'maatschappij', 'pvmg', 'PP/mij', 'Praktijkgerichte programma''s', 'praktijkgericht vak', 'pv maatschappij groot', 'praktijkgericht vak maatschappij (groot)'),
(340, 'technologie', 'pvtg', 'te', 'Praktijkgerichte programma''s', 'praktijkgericht vak', 'pv technologie groot', 'praktijkgericht vak technologie (groot)'),
(341, 'educatie', 'pred', 'PP/ed', 'Praktijkgerichte programma''s', 'praktijkroute', 'pp praktijkroute educatie', 'praktijkroute havo-educatie'),
(342, 'rekenen', 'R3F', 'RW/rek', 'Rekenen en wiskunde', NULL, 'rekenen 3F', 'rekenen 3F'),
(343, 'rekenen en wiskunde', NULL, 'rw', 'Rekenen en wiskunde', NULL, NULL, NULL),
(344, 'gecijferdheid', 'bge', 'RW/cijf', 'Rekenen en wiskunde', NULL, 'bepr gecijferdheid', 'beproeving gecijferdheid'),
(345, 'wiskunde', 'wi', 'wi', 'Rekenen en wiskunde', NULL, 'wiskunde', 'wiskunde'),
(346, 'wiskunde A', 'wisA', 'wisA', 'Rekenen en wiskunde', NULL, 'wiskunde A', 'wiskunde A'),
(347, 'wiskunde B', 'wisB', 'wisB', 'Rekenen en wiskunde', NULL, 'wiskunde B', 'wiskunde B'),
(348, 'wiskunde C', 'wisC', 'wisC', 'Rekenen en wiskunde', NULL, 'wiskunde C', 'wiskunde C'),
(349, 'wiskunde D', 'wisD', 'wisD', 'Rekenen en wiskunde', NULL, 'wiskunde D', 'wiskunde D'),
(350, 'beproeving wiskunde cultuur en maatschappij', 'bwcm', 'RW/cm', 'Rekenen en wiskunde', NULL, 'bepr wiskunde cult maats', 'beproeving wiskunde cultuur en maatschappij'),
(351, 'beproeving wiskunde economie en maatschappij', 'bwem', 'RW/em', 'Rekenen en wiskunde', NULL, 'bepr wiskunde eco maats', 'beproeving wiskunde economie en maatschappij'),
(352, 'beproeving wiskunde natuur en gezondheid', 'bwng', 'RW/ng', 'Rekenen en wiskunde', NULL, 'bepr wiskunde nat gez', 'beproeving wiskunde natuur en gezondheid'),
(353, 'beproeving wiskunde natuur en techniek', 'bwnt', 'RW/nt', 'Rekenen en wiskunde', NULL, 'bepr wiskunde nat tech', 'beproeving wiskunde natuur en techniek'),
(354, 'leergebied overstijgende vaardigheden', NULL, 'lov', 'vso', NULL, NULL, NULL),
(355, 'voorbereiding op arbeid', NULL, 'voa', 'vso', NULL, NULL, NULL),
(356, 'voorbereiding op dagbesteding', NULL, 'vodb', 'vso', NULL, NULL, NULL);

INSERT INTO `subject_levels`
  (`subject_id`, `level`, `code`, `exam_year_from`, `exam_year_to`, `sweep_year`) VALUES

(2, 'havo', '1061', NULL, NULL, NULL),
(2, 'vwo', '1061', NULL, NULL, NULL),
(6, 'vwo', '1131', 2021, NULL, NULL),
(7, 'vwo', '1133', 2023, NULL, NULL),
(8, 'vwo', '1134', 2023, NULL, NULL),
(9, 'havo', '1055', NULL, NULL, NULL),
(9, 'vwo', '1055', NULL, NULL, NULL),
(10, 'bb', '1200', NULL, NULL, NULL),
(10, 'kb', '1200', NULL, NULL, NULL),
(10, 'gl', '1200', NULL, NULL, NULL),
(11, 'bb', '1202', NULL, NULL, NULL),
(11, 'kb', '1202', NULL, NULL, NULL),
(11, 'gl', '1202', NULL, NULL, NULL),
(12, 'bb', '1201', NULL, NULL, NULL),
(12, 'kb', '1201', NULL, NULL, NULL),
(12, 'gl', '1201', NULL, NULL, NULL),
(13, 'bb', '1204', NULL, NULL, NULL),
(13, 'kb', '1204', NULL, NULL, NULL),
(13, 'gl', '1204', NULL, NULL, NULL),
(14, 'bb', '1203', NULL, NULL, NULL),
(14, 'kb', '1203', NULL, NULL, NULL),
(14, 'gl', '1203', NULL, NULL, NULL),
(15, 'bb', '1229', NULL, NULL, NULL),
(15, 'kb', '1229', NULL, NULL, NULL),
(15, 'gl', '1229', NULL, NULL, NULL),
(16, 'bb', '1214', NULL, NULL, NULL),
(16, 'kb', '1214', NULL, NULL, NULL),
(16, 'gl', '1214', NULL, NULL, NULL),
(17, 'bb', '1221', NULL, NULL, NULL),
(17, 'kb', '1221', NULL, NULL, NULL),
(17, 'gl', '1221', NULL, NULL, NULL),
(18, 'bb', '1224', NULL, NULL, NULL),
(18, 'kb', '1224', NULL, NULL, NULL),
(18, 'gl', '1224', NULL, NULL, NULL),
(19, 'bb', '1213', NULL, NULL, NULL),
(19, 'kb', '1213', NULL, NULL, NULL),
(19, 'gl', '1213', NULL, NULL, NULL),
(20, 'bb', '1205', NULL, NULL, NULL),
(20, 'kb', '1205', NULL, NULL, NULL),
(20, 'gl', '1205', NULL, NULL, NULL),
(21, 'bb', '1225', NULL, NULL, NULL),
(21, 'kb', '1225', NULL, NULL, NULL),
(21, 'gl', '1225', NULL, NULL, NULL),
(22, 'bb', '1232', 2022, NULL, NULL),
(22, 'kb', '1232', 2022, NULL, NULL),
(22, 'gl', '1232', 2022, NULL, NULL),
(23, 'bb', '1233', 2026, NULL, NULL),
(23, 'kb', '1233', 2026, NULL, NULL),
(23, 'gl', '1233', 2026, NULL, NULL),
(24, 'bb', '1210', NULL, NULL, NULL),
(24, 'kb', '1210', NULL, NULL, NULL),
(24, 'gl', '1210', NULL, NULL, NULL),
(25, 'bb', '1227', NULL, NULL, NULL),
(25, 'kb', '1227', NULL, NULL, NULL),
(25, 'gl', '1227', NULL, NULL, NULL),
(26, 'bb', '1208', NULL, NULL, NULL),
(26, 'kb', '1208', NULL, NULL, NULL),
(26, 'gl', '1208', NULL, NULL, NULL),
(27, 'bb', '1223', NULL, NULL, NULL),
(27, 'kb', '1223', NULL, NULL, NULL),
(27, 'gl', '1223', NULL, NULL, NULL),
(28, 'bb', '1220', NULL, NULL, NULL),
(28, 'kb', '1220', NULL, NULL, NULL),
(28, 'gl', '1220', NULL, NULL, NULL),
(29, 'bb', '1231', 2020, NULL, NULL),
(29, 'kb', '1231', 2020, NULL, NULL),
(29, 'gl', '1231', 2020, NULL, NULL),
(30, 'bb', '1218', NULL, NULL, NULL),
(30, 'kb', '1218', NULL, NULL, NULL),
(30, 'gl', '1218', NULL, NULL, NULL),
(31, 'bb', '1215', NULL, NULL, NULL),
(31, 'kb', '1215', NULL, NULL, NULL),
(31, 'gl', '1215', NULL, NULL, NULL),
(32, 'bb', '1226', NULL, NULL, NULL),
(32, 'kb', '1226', NULL, NULL, NULL),
(32, 'gl', '1226', NULL, NULL, NULL),
(33, 'bb', '1207', NULL, NULL, NULL),
(33, 'kb', '1207', NULL, NULL, NULL),
(33, 'gl', '1207', NULL, NULL, NULL),
(34, 'bb', '1206', NULL, NULL, NULL),
(34, 'kb', '1206', NULL, NULL, NULL),
(34, 'gl', '1206', NULL, NULL, NULL),
(35, 'bb', '1230', 2020, NULL, NULL),
(35, 'kb', '1230', 2020, NULL, NULL),
(35, 'gl', '1230', 2020, NULL, NULL),
(36, 'bb', '1222', NULL, NULL, NULL),
(36, 'kb', '1222', NULL, NULL, NULL),
(36, 'gl', '1222', NULL, NULL, NULL),
(37, 'bb', '1212', NULL, NULL, NULL),
(37, 'kb', '1212', NULL, NULL, NULL),
(37, 'gl', '1212', NULL, NULL, NULL),
(38, 'bb', '1216', NULL, NULL, NULL),
(38, 'kb', '1216', NULL, NULL, NULL),
(38, 'gl', '1216', NULL, NULL, NULL),
(39, 'bb', '1095', NULL, NULL, NULL),
(39, 'kb', '1095', NULL, NULL, NULL),
(39, 'gl', '1095', NULL, NULL, NULL),
(40, 'bb', '1900', NULL, NULL, NULL),
(40, 'kb', '1900', NULL, NULL, NULL),
(40, 'gl', '1900', NULL, NULL, NULL),
(41, 'bb', '1915', NULL, NULL, NULL),
(41, 'kb', '1915', NULL, NULL, NULL),
(41, 'gl', '1915', NULL, NULL, NULL),
(42, 'bb', '1902', NULL, NULL, NULL),
(42, 'kb', '1902', NULL, NULL, NULL),
(42, 'gl', '1902', NULL, NULL, NULL),
(43, 'bb', '1903', NULL, NULL, NULL),
(43, 'kb', '1903', NULL, NULL, NULL),
(43, 'gl', '1903', NULL, NULL, NULL),
(44, 'bb', '1904', NULL, NULL, NULL),
(44, 'kb', '1904', NULL, NULL, NULL),
(44, 'gl', '1904', NULL, NULL, NULL),
(45, 'bb', '1918', NULL, NULL, NULL),
(45, 'kb', '1918', NULL, NULL, NULL),
(45, 'gl', '1918', NULL, NULL, NULL),
(46, 'bb', '1911', NULL, NULL, NULL),
(46, 'kb', '1911', NULL, NULL, NULL),
(46, 'gl', '1911', NULL, NULL, NULL),
(47, 'bb', '1910', NULL, NULL, NULL),
(47, 'kb', '1910', NULL, NULL, NULL),
(47, 'gl', '1910', NULL, NULL, NULL),
(49, 'bb', '1914', NULL, NULL, NULL),
(49, 'kb', '1914', NULL, NULL, NULL),
(49, 'gl', '1914', NULL, NULL, NULL),
(50, 'bb', '1909', NULL, NULL, NULL),
(50, 'kb', '1909', NULL, NULL, NULL),
(50, 'gl', '1909', NULL, NULL, NULL),
(51, 'bb', '1906', NULL, NULL, NULL),
(51, 'kb', '1906', NULL, NULL, NULL),
(51, 'gl', '1906', NULL, NULL, NULL),
(52, 'bb', '1917', NULL, NULL, NULL),
(52, 'kb', '1917', NULL, NULL, NULL),
(52, 'gl', '1917', NULL, NULL, NULL),
(53, 'bb', '1913', NULL, NULL, NULL),
(53, 'kb', '1913', NULL, NULL, NULL),
(53, 'gl', '1913', NULL, NULL, NULL),
(54, 'bb', '1912', NULL, NULL, NULL),
(54, 'kb', '1912', NULL, NULL, NULL),
(54, 'gl', '1912', NULL, NULL, NULL),
(56, 'bb', '1630', 2022, NULL, NULL),
(56, 'kb', '1630', 2022, NULL, NULL),
(56, 'gl', '1630', 2022, NULL, NULL),
(57, 'bb', '1631', 2022, NULL, NULL),
(57, 'kb', '1631', 2022, NULL, NULL),
(57, 'gl', '1631', 2022, NULL, NULL),
(58, 'bb', '1632', 2022, NULL, NULL),
(58, 'kb', '1632', 2022, NULL, NULL),
(58, 'gl', '1632', 2022, NULL, NULL),
(59, 'bb', '1700', NULL, 2025, 2026),
(59, 'kb', '1700', NULL, 2025, 2026),
(59, 'gl', '1700', NULL, 2025, 2026),
(60, 'bb', '1723', 2024, NULL, NULL),
(60, 'kb', '1723', 2024, NULL, NULL),
(60, 'gl', '1723', 2024, NULL, NULL),
(61, 'bb', '1724', 2024, NULL, NULL),
(61, 'kb', '1724', 2024, NULL, NULL),
(61, 'gl', '1724', 2024, NULL, NULL),
(62, 'bb', '1725', 2024, NULL, NULL),
(62, 'kb', '1725', 2024, NULL, NULL),
(62, 'gl', '1725', 2024, NULL, NULL),
(63, 'bb', '1726', 2024, NULL, NULL),
(63, 'kb', '1726', 2024, NULL, NULL),
(63, 'gl', '1726', 2024, NULL, NULL),
(64, 'bb', '1704', NULL, 2025, NULL),
(64, 'kb', '1704', NULL, 2025, NULL),
(64, 'gl', '1704', NULL, 2025, NULL),
(65, 'bb', '1701', NULL, 2025, NULL),
(65, 'kb', '1701', NULL, 2025, NULL),
(65, 'gl', '1701', NULL, 2025, NULL),
(66, 'bb', '1703', NULL, 2025, NULL),
(66, 'kb', '1703', NULL, 2025, NULL),
(66, 'gl', '1703', NULL, 2025, NULL),
(67, 'bb', '1702', 2024, 2025, NULL),
(67, 'kb', '1702', 2024, 2025, NULL),
(67, 'gl', '1702', 2024, 2025, NULL),
(68, 'bb', '1716', NULL, NULL, NULL),
(68, 'kb', '1716', NULL, NULL, NULL),
(68, 'gl', '1716', NULL, NULL, NULL),
(69, 'bb', '1717', NULL, NULL, NULL),
(69, 'kb', '1717', NULL, NULL, NULL),
(69, 'gl', '1717', NULL, NULL, NULL),
(71, 'bb', '1720', NULL, NULL, NULL),
(71, 'kb', '1720', NULL, NULL, NULL),
(71, 'gl', '1720', NULL, NULL, NULL),
(72, 'bb', '1714', NULL, NULL, NULL),
(72, 'kb', '1714', NULL, NULL, NULL),
(72, 'gl', '1714', NULL, NULL, NULL),
(73, 'bb', '1712', NULL, NULL, NULL),
(73, 'kb', '1712', NULL, NULL, NULL),
(73, 'gl', '1712', NULL, NULL, NULL),
(74, 'bb', '1715', NULL, NULL, NULL),
(74, 'kb', '1715', NULL, NULL, NULL),
(74, 'gl', '1715', NULL, NULL, NULL),
(75, 'bb', '1709', NULL, NULL, NULL),
(75, 'kb', '1709', NULL, NULL, NULL),
(75, 'gl', '1709', NULL, NULL, NULL),
(76, 'bb', '1718', NULL, NULL, NULL),
(76, 'kb', '1718', NULL, NULL, NULL),
(76, 'gl', '1718', NULL, NULL, NULL),
(77, 'bb', '1710', 2020, NULL, NULL),
(77, 'kb', '1710', 2020, NULL, NULL),
(77, 'gl', '1710', 2020, NULL, NULL),
(78, 'bb', '1719', NULL, NULL, NULL),
(78, 'kb', '1719', NULL, NULL, NULL),
(78, 'gl', '1719', NULL, NULL, NULL),
(79, 'bb', '1721', NULL, NULL, NULL),
(79, 'kb', '1721', NULL, NULL, NULL),
(79, 'gl', '1721', NULL, NULL, NULL),
(80, 'bb', '2021', NULL, NULL, NULL),
(80, 'kb', '2021', NULL, NULL, NULL),
(80, 'gl', '2021', NULL, NULL, NULL),
(81, 'bb', '2008', NULL, NULL, NULL),
(81, 'kb', '2008', NULL, NULL, NULL),
(81, 'gl', '2008', NULL, NULL, NULL),
(82, 'bb', '2023', 2022, NULL, NULL),
(82, 'kb', '2023', 2022, NULL, NULL),
(82, 'gl', '2023', 2022, NULL, NULL),
(83, 'bb', '2025', 2026, NULL, NULL),
(83, 'kb', '2025', 2026, NULL, NULL),
(83, 'gl', '2025', 2026, NULL, NULL),
(84, 'bb', '2013', NULL, NULL, NULL),
(84, 'kb', '2013', NULL, NULL, NULL),
(84, 'gl', '2013', NULL, NULL, NULL),
(85, 'bb', '2011', NULL, NULL, NULL),
(85, 'kb', '2011', NULL, NULL, NULL),
(85, 'gl', '2011', NULL, NULL, NULL),
(86, 'bb', '2019', NULL, NULL, NULL),
(86, 'kb', '2019', NULL, NULL, NULL),
(86, 'gl', '2019', NULL, NULL, NULL),
(87, 'bb', '2000', NULL, NULL, NULL),
(87, 'kb', '2000', NULL, NULL, NULL),
(87, 'gl', '2000', NULL, NULL, NULL),
(88, 'bb', '2001', NULL, NULL, NULL),
(88, 'kb', '2001', NULL, NULL, NULL),
(88, 'gl', '2001', NULL, NULL, NULL),
(89, 'bb', '2009', NULL, NULL, NULL),
(89, 'kb', '2009', NULL, NULL, NULL),
(89, 'gl', '2009', NULL, NULL, NULL),
(90, 'bb', '2004', NULL, NULL, NULL),
(90, 'kb', '2004', NULL, NULL, NULL),
(90, 'gl', '2004', NULL, NULL, NULL),
(91, 'bb', '2016', NULL, NULL, NULL),
(91, 'kb', '2016', NULL, NULL, NULL),
(91, 'gl', '2016', NULL, NULL, NULL),
(92, 'bb', '2005', NULL, NULL, NULL),
(92, 'kb', '2005', NULL, NULL, NULL),
(92, 'gl', '2005', NULL, NULL, NULL),
(93, 'bb', '2012', NULL, NULL, NULL),
(93, 'kb', '2012', NULL, NULL, NULL),
(93, 'gl', '2012', NULL, NULL, NULL),
(94, 'bb', '2017', NULL, NULL, NULL),
(94, 'kb', '2017', NULL, NULL, NULL),
(94, 'gl', '2017', NULL, NULL, NULL),
(95, 'bb', '2006', NULL, NULL, NULL),
(95, 'kb', '2006', NULL, NULL, NULL),
(95, 'gl', '2006', NULL, NULL, NULL),
(96, 'bb', '2002', NULL, NULL, NULL),
(96, 'kb', '2002', NULL, NULL, NULL),
(96, 'gl', '2002', NULL, NULL, NULL),
(97, 'bb', '2018', NULL, NULL, NULL),
(97, 'kb', '2018', NULL, NULL, NULL),
(97, 'gl', '2018', NULL, NULL, NULL),
(98, 'bb', '2022', 2020, NULL, NULL),
(98, 'kb', '2022', 2020, NULL, NULL),
(98, 'gl', '2022', 2020, NULL, NULL),
(99, 'bb', '2020', NULL, NULL, NULL),
(99, 'kb', '2020', NULL, NULL, NULL),
(99, 'gl', '2020', NULL, NULL, NULL),
(100, 'bb', '2014', NULL, NULL, NULL),
(100, 'kb', '2014', NULL, NULL, NULL),
(100, 'gl', '2014', NULL, NULL, NULL),
(101, 'bb', '2007', NULL, NULL, NULL),
(101, 'kb', '2007', NULL, NULL, NULL),
(101, 'gl', '2007', NULL, NULL, NULL),
(102, 'bb', '1800', NULL, NULL, NULL),
(102, 'kb', '1800', NULL, NULL, NULL),
(102, 'gl', '1800', NULL, NULL, NULL),
(103, 'bb', '1801', NULL, NULL, NULL),
(103, 'kb', '1801', NULL, NULL, NULL),
(103, 'gl', '1801', NULL, NULL, NULL),
(104, 'bb', '1803', NULL, NULL, NULL),
(104, 'kb', '1803', NULL, NULL, NULL),
(104, 'gl', '1803', NULL, NULL, NULL),
(105, 'bb', '1802', NULL, NULL, NULL),
(105, 'kb', '1802', NULL, NULL, NULL),
(105, 'gl', '1802', NULL, NULL, NULL),
(106, 'bb', '1804', NULL, NULL, NULL),
(106, 'kb', '1804', NULL, NULL, NULL),
(106, 'gl', '1804', NULL, NULL, NULL),
(107, 'bb', '1818', NULL, NULL, NULL),
(107, 'kb', '1818', NULL, NULL, NULL),
(107, 'gl', '1818', NULL, NULL, NULL),
(110, 'bb', '1810', NULL, NULL, NULL),
(110, 'kb', '1810', NULL, NULL, NULL),
(110, 'gl', '1810', NULL, NULL, NULL),
(111, 'bb', '1820', NULL, NULL, NULL),
(111, 'kb', '1820', NULL, NULL, NULL),
(111, 'gl', '1820', NULL, NULL, NULL),
(112, 'bb', '1821', NULL, NULL, NULL),
(112, 'kb', '1821', NULL, NULL, NULL),
(112, 'gl', '1821', NULL, NULL, NULL),
(113, 'bb', '1817', NULL, NULL, NULL),
(113, 'kb', '1817', NULL, NULL, NULL),
(113, 'gl', '1817', NULL, NULL, NULL),
(114, 'bb', '1819', NULL, NULL, NULL),
(114, 'kb', '1819', NULL, NULL, NULL),
(114, 'gl', '1819', NULL, NULL, NULL),
(115, 'bb', '1809', NULL, NULL, NULL),
(115, 'kb', '1809', NULL, NULL, NULL),
(115, 'gl', '1809', NULL, NULL, NULL),
(116, 'bb', '1822', 2021, NULL, NULL),
(116, 'kb', '1822', 2021, NULL, NULL),
(116, 'gl', '1822', 2021, NULL, NULL),
(117, 'bb', '1811', NULL, NULL, NULL),
(117, 'kb', '1811', NULL, NULL, NULL),
(117, 'gl', '1811', NULL, NULL, NULL),
(118, 'bb', '2100', NULL, NULL, NULL),
(118, 'kb', '2100', NULL, NULL, NULL),
(118, 'gl', '2100', NULL, NULL, NULL),
(119, 'bb', '2101', NULL, NULL, NULL),
(119, 'kb', '2101', NULL, NULL, NULL),
(119, 'gl', '2101', NULL, NULL, NULL),
(120, 'bb', '2102', NULL, NULL, NULL),
(120, 'kb', '2102', NULL, NULL, NULL),
(120, 'gl', '2102', NULL, NULL, NULL),
(121, 'bb', '2103', NULL, NULL, NULL),
(121, 'kb', '2103', NULL, NULL, NULL),
(121, 'gl', '2103', NULL, NULL, NULL),
(122, 'bb', '2104', NULL, NULL, NULL),
(122, 'kb', '2104', NULL, NULL, NULL),
(122, 'gl', '2104', NULL, NULL, NULL),
(123, 'gl', '2115', NULL, NULL, NULL),
(124, 'bb', '2121', NULL, NULL, NULL),
(124, 'kb', '2121', NULL, NULL, NULL),
(124, 'gl', '2121', NULL, NULL, NULL),
(125, 'bb', '2119', NULL, NULL, NULL),
(125, 'kb', '2119', NULL, NULL, NULL),
(125, 'gl', '2119', NULL, NULL, NULL),
(126, 'bb', '2110', NULL, NULL, NULL),
(126, 'kb', '2110', NULL, NULL, NULL),
(126, 'gl', '2110', NULL, NULL, NULL),
(127, 'gl', '2114', NULL, NULL, NULL),
(128, 'bb', '2113', NULL, NULL, NULL),
(128, 'kb', '2113', NULL, NULL, NULL),
(128, 'gl', '2113', NULL, NULL, NULL),
(129, 'bb', '2106', NULL, NULL, NULL),
(129, 'kb', '2106', NULL, NULL, NULL),
(129, 'gl', '2106', NULL, NULL, NULL),
(130, 'bb', '2118', NULL, NULL, NULL),
(130, 'kb', '2118', NULL, NULL, NULL),
(130, 'gl', '2118', NULL, NULL, NULL),
(131, 'bb', '2116', NULL, NULL, NULL),
(131, 'kb', '2116', NULL, NULL, NULL),
(131, 'gl', '2116', NULL, NULL, NULL),
(132, 'bb', '2107', NULL, NULL, NULL),
(132, 'kb', '2107', NULL, NULL, NULL),
(132, 'gl', '2107', NULL, NULL, NULL),
(133, 'bb', '2111', NULL, NULL, NULL),
(133, 'kb', '2111', NULL, NULL, NULL),
(133, 'gl', '2111', NULL, NULL, NULL),
(134, 'bb', '2117', NULL, NULL, NULL),
(134, 'kb', '2117', NULL, NULL, NULL),
(134, 'gl', '2117', NULL, NULL, NULL),
(135, 'bb', '2108', NULL, NULL, NULL),
(135, 'kb', '2108', NULL, NULL, NULL),
(135, 'gl', '2108', NULL, NULL, NULL),
(136, 'bb', '2120', NULL, NULL, NULL),
(136, 'kb', '2120', NULL, NULL, NULL),
(136, 'gl', '2120', NULL, NULL, NULL),
(137, 'bb', '2105', NULL, NULL, NULL),
(137, 'kb', '2105', NULL, NULL, NULL),
(137, 'gl', '2105', NULL, NULL, NULL),
(138, 'bb', '2109', NULL, NULL, NULL),
(138, 'kb', '2109', NULL, NULL, NULL),
(138, 'gl', '2109', NULL, NULL, NULL),
(139, 'bb', '0692', NULL, NULL, NULL),
(139, 'kb', '0692', NULL, NULL, NULL),
(139, 'gl', '0692', NULL, NULL, NULL),
(140, 'bb', '0691', NULL, NULL, NULL),
(140, 'kb', '0691', NULL, NULL, NULL),
(140, 'gl', '0691', NULL, NULL, NULL),
(141, 'bb', '1400', NULL, NULL, NULL),
(141, 'kb', '1400', NULL, NULL, NULL),
(141, 'gl', '1400', NULL, NULL, NULL),
(142, 'bb', '1401', NULL, NULL, NULL),
(142, 'kb', '1401', NULL, NULL, NULL),
(142, 'gl', '1401', NULL, NULL, NULL),
(143, 'bb', '1402', NULL, NULL, NULL),
(143, 'kb', '1402', NULL, NULL, NULL),
(143, 'gl', '1402', NULL, NULL, NULL),
(144, 'bb', '1403', NULL, NULL, NULL),
(144, 'kb', '1403', NULL, NULL, NULL),
(144, 'gl', '1403', NULL, NULL, NULL),
(145, 'bb', '1404', NULL, NULL, NULL),
(145, 'kb', '1404', NULL, NULL, NULL),
(145, 'gl', '1404', NULL, NULL, NULL),
(146, 'bb', '1406', NULL, NULL, NULL),
(146, 'kb', '1406', NULL, NULL, NULL),
(146, 'gl', '1406', NULL, NULL, NULL),
(147, 'bb', '1412', NULL, NULL, NULL),
(147, 'kb', '1412', NULL, NULL, NULL),
(147, 'gl', '1412', NULL, NULL, NULL),
(148, 'bb', '1408', NULL, NULL, NULL),
(148, 'kb', '1408', NULL, NULL, NULL),
(148, 'gl', '1408', NULL, NULL, NULL),
(149, 'bb', '1411', NULL, NULL, NULL),
(149, 'kb', '1411', NULL, NULL, NULL),
(149, 'gl', '1411', NULL, NULL, NULL),
(150, 'bb', '1419', NULL, NULL, NULL),
(150, 'kb', '1419', NULL, NULL, NULL),
(150, 'gl', '1419', NULL, NULL, NULL),
(151, 'bb', '1407', 2022, NULL, NULL),
(151, 'kb', '1407', 2022, NULL, NULL),
(151, 'gl', '1407', 2022, NULL, NULL),
(152, 'bb', '1409', NULL, NULL, NULL),
(152, 'kb', '1409', NULL, NULL, NULL),
(152, 'gl', '1409', NULL, NULL, NULL),
(154, 'bb', '1410', NULL, NULL, NULL),
(154, 'kb', '1410', NULL, NULL, NULL),
(154, 'gl', '1410', NULL, NULL, NULL),
(156, 'bb', '1415', NULL, NULL, NULL),
(156, 'kb', '1415', NULL, NULL, NULL),
(156, 'gl', '1415', NULL, NULL, NULL),
(157, 'bb', '1405', NULL, NULL, NULL),
(157, 'kb', '1405', NULL, NULL, NULL),
(157, 'gl', '1405', NULL, NULL, NULL),
(158, 'bb', '1416', NULL, NULL, NULL),
(158, 'kb', '1416', NULL, NULL, NULL),
(158, 'gl', '1416', NULL, NULL, NULL),
(159, 'bb', '1414', NULL, NULL, NULL),
(159, 'kb', '1414', NULL, NULL, NULL),
(159, 'gl', '1414', NULL, NULL, NULL),
(160, 'bb', '1413', NULL, NULL, NULL),
(160, 'kb', '1413', NULL, NULL, NULL),
(160, 'gl', '1413', NULL, NULL, NULL),
(161, 'bb', '1500', NULL, NULL, NULL),
(161, 'kb', '1500', NULL, NULL, NULL),
(161, 'gl', '1500', NULL, NULL, NULL),
(162, 'bb', '1501', NULL, NULL, NULL),
(162, 'kb', '1501', NULL, NULL, NULL),
(162, 'gl', '1501', NULL, NULL, NULL),
(163, 'bb', '1502', NULL, NULL, NULL),
(163, 'kb', '1502', NULL, NULL, NULL),
(163, 'gl', '1502', NULL, NULL, NULL),
(164, 'bb', '1503', NULL, NULL, NULL),
(164, 'kb', '1503', NULL, NULL, NULL),
(164, 'gl', '1503', NULL, NULL, NULL),
(165, 'bb', '1504', NULL, NULL, NULL),
(165, 'kb', '1504', NULL, NULL, NULL),
(165, 'gl', '1504', NULL, NULL, NULL),
(166, 'bb', '1505', NULL, NULL, NULL),
(166, 'kb', '1505', NULL, NULL, NULL),
(166, 'gl', '1505', NULL, NULL, NULL),
(167, 'bb', '1513', NULL, NULL, NULL),
(167, 'kb', '1513', NULL, NULL, NULL),
(167, 'gl', '1513', NULL, NULL, NULL),
(168, 'bb', '1514', NULL, NULL, NULL),
(168, 'kb', '1514', NULL, NULL, NULL),
(168, 'gl', '1514', NULL, NULL, NULL),
(169, 'bb', '1511', NULL, NULL, NULL),
(169, 'kb', '1511', NULL, NULL, NULL),
(169, 'gl', '1511', NULL, NULL, NULL),
(170, 'bb', '1510', NULL, NULL, NULL),
(170, 'kb', '1510', NULL, NULL, NULL),
(170, 'gl', '1510', NULL, NULL, NULL),
(171, 'bb', '1506', NULL, NULL, NULL),
(171, 'kb', '1506', NULL, NULL, NULL),
(171, 'gl', '1506', NULL, NULL, NULL),
(172, 'bb', '1517', 2020, NULL, NULL),
(172, 'kb', '1517', 2020, NULL, NULL),
(172, 'gl', '1517', 2020, NULL, NULL),
(173, 'bb', '1512', NULL, NULL, NULL),
(173, 'kb', '1512', NULL, NULL, NULL),
(173, 'gl', '1512', NULL, NULL, NULL),
(174, 'bb', '1507', NULL, NULL, NULL),
(174, 'kb', '1507', NULL, NULL, NULL),
(174, 'gl', '1507', NULL, NULL, NULL),
(175, 'bb', '1508', NULL, NULL, NULL),
(175, 'kb', '1508', NULL, NULL, NULL),
(175, 'gl', '1508', NULL, NULL, NULL),
(176, 'bb', '1515', NULL, NULL, NULL),
(176, 'kb', '1515', NULL, NULL, NULL),
(176, 'gl', '1515', NULL, NULL, NULL),
(177, 'bb', '1509', NULL, NULL, NULL),
(177, 'kb', '1509', NULL, NULL, NULL),
(178, 'bb', '1516', NULL, NULL, NULL),
(178, 'kb', '1516', NULL, NULL, NULL),
(178, 'gl', '1516', NULL, NULL, NULL),
(179, 'bb', '1300', NULL, NULL, NULL),
(179, 'kb', '1300', NULL, NULL, NULL),
(179, 'gl', '1300', NULL, NULL, NULL),
(180, 'bb', '1301', NULL, NULL, NULL),
(180, 'kb', '1301', NULL, NULL, NULL),
(180, 'gl', '1301', NULL, NULL, NULL),
(181, 'bb', '1302', NULL, NULL, NULL),
(181, 'kb', '1302', NULL, NULL, NULL),
(181, 'gl', '1302', NULL, NULL, NULL),
(182, 'bb', '1303', NULL, NULL, NULL),
(182, 'kb', '1303', NULL, NULL, NULL),
(182, 'gl', '1303', NULL, NULL, NULL),
(183, 'bb', '1304', NULL, NULL, NULL),
(183, 'kb', '1304', NULL, NULL, NULL),
(183, 'gl', '1304', NULL, NULL, NULL),
(184, 'bb', '1326', NULL, NULL, NULL),
(184, 'kb', '1326', NULL, NULL, NULL),
(184, 'gl', '1326', NULL, NULL, NULL),
(185, 'bb', '1333', 2020, NULL, NULL),
(185, 'kb', '1333', 2020, NULL, NULL),
(185, 'gl', '1333', 2020, NULL, NULL),
(186, 'bb', '1313', NULL, NULL, NULL),
(186, 'kb', '1313', NULL, NULL, NULL),
(186, 'gl', '1313', NULL, NULL, NULL),
(187, 'bb', '1316', NULL, NULL, NULL),
(187, 'kb', '1316', NULL, NULL, NULL),
(187, 'gl', '1316', NULL, NULL, NULL),
(188, 'bb', '1329', NULL, NULL, NULL),
(188, 'kb', '1329', NULL, NULL, NULL),
(188, 'gl', '1329', NULL, NULL, NULL),
(189, 'bb', '1314', NULL, NULL, NULL),
(189, 'kb', '1314', NULL, NULL, NULL),
(189, 'gl', '1314', NULL, NULL, NULL),
(190, 'bb', '1335', 2021, NULL, NULL),
(190, 'kb', '1335', 2021, NULL, NULL),
(190, 'gl', '1335', 2021, NULL, NULL),
(191, 'bb', '1336', 2021, NULL, NULL),
(191, 'kb', '1336', 2021, NULL, NULL),
(191, 'gl', '1336', 2021, NULL, NULL),
(192, 'bb', '1327', NULL, NULL, NULL),
(192, 'kb', '1327', NULL, NULL, NULL),
(192, 'gl', '1327', NULL, NULL, NULL),
(193, 'bb', '1337', 2023, NULL, NULL),
(193, 'kb', '1337', 2023, NULL, NULL),
(193, 'gl', '1337', 2023, NULL, NULL),
(194, 'bb', '1307', NULL, NULL, NULL),
(194, 'kb', '1307', NULL, NULL, NULL),
(194, 'gl', '1307', NULL, NULL, NULL),
(195, 'bb', '1330', NULL, NULL, NULL),
(195, 'kb', '1330', NULL, NULL, NULL),
(195, 'gl', '1330', NULL, NULL, NULL),
(196, 'kb', '1332', 2018, NULL, NULL),
(196, 'gl', '1332', 2018, NULL, NULL),
(197, 'bb', '1315', NULL, NULL, NULL),
(197, 'kb', '1315', NULL, NULL, NULL),
(197, 'gl', '1315', NULL, NULL, NULL),
(198, 'bb', '1331', NULL, NULL, NULL),
(198, 'kb', '1331', NULL, NULL, NULL),
(198, 'gl', '1331', NULL, NULL, NULL),
(199, 'bb', '1322', NULL, NULL, NULL),
(199, 'kb', '1322', NULL, NULL, NULL),
(199, 'gl', '1322', NULL, NULL, NULL),
(200, 'bb', '1228', NULL, NULL, NULL),
(200, 'kb', '1228', NULL, NULL, NULL),
(200, 'gl', '1228', NULL, NULL, NULL),
(201, 'bb', '1305', NULL, NULL, NULL),
(201, 'kb', '1305', NULL, NULL, NULL),
(201, 'gl', '1305', NULL, NULL, NULL),
(202, 'bb', '1328', NULL, NULL, NULL),
(202, 'kb', '1328', NULL, NULL, NULL),
(202, 'gl', '1328', NULL, NULL, NULL),
(203, 'bb', '1308', NULL, NULL, NULL),
(203, 'kb', '1308', NULL, NULL, NULL),
(203, 'gl', '1308', NULL, NULL, NULL),
(204, 'bb', '1334', 2020, NULL, NULL),
(204, 'kb', '1334', 2020, NULL, NULL),
(204, 'gl', '1334', 2020, NULL, NULL),
(205, 'bb', '1311', NULL, NULL, NULL),
(205, 'kb', '1311', NULL, NULL, NULL),
(205, 'gl', '1311', NULL, NULL, NULL),
(206, 'bb', '1317', NULL, NULL, NULL),
(206, 'kb', '1317', NULL, NULL, NULL),
(206, 'gl', '1317', NULL, NULL, NULL),
(207, 'bb', '1338', 2023, NULL, NULL),
(207, 'kb', '1338', 2023, NULL, NULL),
(207, 'gl', '1338', 2023, NULL, NULL),
(208, 'bb', '1340', 2026, NULL, NULL),
(208, 'kb', '1340', 2026, NULL, NULL),
(208, 'gl', '1340', 2026, NULL, NULL),
(209, 'bb', '1310', NULL, NULL, NULL),
(209, 'kb', '1310', NULL, NULL, NULL),
(209, 'gl', '1310', NULL, NULL, NULL),
(210, 'bb', '1318', NULL, NULL, NULL),
(210, 'kb', '1318', NULL, NULL, NULL),
(210, 'gl', '1318', NULL, NULL, NULL),
(211, 'bb', '1600', NULL, NULL, NULL),
(211, 'kb', '1600', NULL, NULL, NULL),
(211, 'gl', '1600', NULL, NULL, NULL),
(212, 'bb', '1601', NULL, NULL, NULL),
(212, 'kb', '1601', NULL, NULL, NULL),
(212, 'gl', '1601', NULL, NULL, NULL),
(213, 'bb', '1602', NULL, NULL, NULL),
(213, 'kb', '1602', NULL, NULL, NULL),
(213, 'gl', '1602', NULL, NULL, NULL),
(214, 'bb', '1603', NULL, NULL, NULL),
(214, 'kb', '1603', NULL, NULL, NULL),
(214, 'gl', '1603', NULL, NULL, NULL),
(215, 'bb', '1604', NULL, NULL, NULL),
(215, 'kb', '1604', NULL, NULL, NULL),
(215, 'gl', '1604', NULL, NULL, NULL),
(216, 'bb', '1624', NULL, NULL, NULL),
(216, 'kb', '1624', NULL, NULL, NULL),
(216, 'gl', '1624', NULL, NULL, NULL),
(217, 'bb', '1614', NULL, 2019, 2020),
(217, 'kb', '1614', NULL, 2019, 2020),
(217, 'gl', '1614', NULL, 2019, 2020),
(218, 'bb', '1622', NULL, 2019, 2020),
(218, 'kb', '1622', NULL, 2019, 2020),
(218, 'gl', '1622', NULL, 2019, 2020),
(219, 'bb', '1612', NULL, 2019, 2020),
(219, 'kb', '1612', NULL, 2019, 2020),
(219, 'gl', '1612', NULL, 2019, 2020),
(220, 'bb', '1626', NULL, NULL, NULL),
(220, 'kb', '1626', NULL, NULL, NULL),
(220, 'gl', '1626', NULL, NULL, NULL),
(221, 'bb', '1621', NULL, 2019, 2020),
(221, 'kb', '1621', NULL, 2019, 2020),
(221, 'gl', '1621', NULL, 2019, 2020),
(222, 'bb', '1627', NULL, NULL, NULL),
(222, 'kb', '1627', NULL, NULL, NULL),
(222, 'gl', '1627', NULL, NULL, NULL),
(223, 'bb', '1606', NULL, NULL, NULL),
(223, 'kb', '1606', NULL, NULL, NULL),
(223, 'gl', '1606', NULL, NULL, NULL),
(224, 'bb', '1608', NULL, NULL, NULL),
(224, 'kb', '1608', NULL, NULL, NULL),
(224, 'gl', '1608', NULL, NULL, NULL),
(225, 'bb', '1607', NULL, NULL, NULL),
(225, 'kb', '1607', NULL, NULL, NULL),
(225, 'gl', '1607', NULL, NULL, NULL),
(226, 'bb', '1623', NULL, NULL, NULL),
(226, 'kb', '1623', NULL, NULL, NULL),
(226, 'gl', '1623', NULL, NULL, NULL),
(227, 'bb', '1628', NULL, NULL, NULL),
(227, 'kb', '1628', NULL, NULL, NULL),
(227, 'gl', '1628', NULL, NULL, NULL),
(228, 'bb', '1619', NULL, 2019, 2020),
(228, 'kb', '1619', NULL, 2019, 2020),
(228, 'gl', '1619', NULL, 2019, 2020),
(229, 'bb', '1616', NULL, 2019, 2020),
(229, 'kb', '1616', NULL, 2019, 2020),
(229, 'gl', '1616', NULL, 2019, 2020),
(230, 'bb', '1629', 2022, NULL, NULL),
(230, 'kb', '1629', 2022, NULL, NULL),
(230, 'gl', '1629', 2022, NULL, NULL),
(231, 'kb', '1611', NULL, 2019, 2020),
(231, 'gl', '1611', NULL, 2019, 2020),
(232, 'bb', '1617', NULL, NULL, NULL),
(232, 'kb', '1617', NULL, NULL, NULL),
(232, 'gl', '1617', NULL, NULL, NULL),
(233, 'bb', '1620', NULL, NULL, NULL),
(233, 'kb', '1620', NULL, NULL, NULL),
(233, 'gl', '1620', NULL, NULL, NULL),
(234, 'bb', '1625', NULL, NULL, NULL),
(234, 'kb', '1625', NULL, NULL, NULL),
(234, 'gl', '1625', NULL, NULL, NULL),
(235, 'bb', '1610', 2025, NULL, NULL),
(235, 'kb', '1610', 2025, NULL, NULL),
(235, 'gl', '1610', 2025, NULL, NULL),
(236, 'bb', '2200', 2025, NULL, NULL),
(236, 'kb', '2200', 2025, NULL, NULL),
(236, 'gl', '2200', 2025, NULL, NULL),
(237, 'bb', '2300', NULL, NULL, NULL),
(237, 'kb', '2300', NULL, NULL, NULL),
(237, 'gl', '2300', NULL, NULL, NULL),
(238, 'bb', '2400', NULL, NULL, NULL),
(238, 'kb', '2400', NULL, NULL, NULL),
(238, 'gl', '2400', NULL, NULL, NULL),
(239, 'bb', '2500', 2027, NULL, NULL),
(239, 'kb', '2500', 2027, NULL, NULL),
(239, 'gl', '2500', 2027, NULL, NULL),
(241, 'havo', '1038', NULL, NULL, NULL),
(241, 'vwo', '1038', NULL, NULL, NULL),
(242, 'bb', '0353', NULL, NULL, NULL),
(242, 'kb', '0353', NULL, NULL, NULL),
(242, 'gl', '0353', NULL, NULL, NULL),
(242, 'tl', '0353', NULL, NULL, NULL),
(242, 'havo', '0353', NULL, NULL, NULL),
(242, 'vwo', '0353', NULL, NULL, NULL),
(243, 'gl', '0352', NULL, NULL, NULL),
(243, 'tl', '0352', NULL, NULL, NULL),
(247, 'havo', '0161', NULL, NULL, NULL),
(247, 'vwo', '0161', NULL, NULL, NULL),
(249, 'vwo', '1111', NULL, NULL, NULL),
(250, 'vwo', '1110', NULL, NULL, NULL),
(251, 'havo', '1093', NULL, NULL, NULL),
(251, 'vwo', '1093', NULL, NULL, NULL),
(252, 'gl', '0420', NULL, NULL, NULL),
(252, 'tl', '0420', NULL, NULL, NULL),
(253, 'havo', '1030', NULL, NULL, NULL),
(253, 'vwo', '1030', NULL, NULL, NULL),
(254, 'havo', '1020', NULL, NULL, NULL),
(254, 'vwo', '1020', NULL, NULL, NULL),
(255, 'bb', '1130', 2019, NULL, NULL),
(255, 'kb', '1130', 2019, NULL, NULL),
(255, 'gl', '1130', 2019, NULL, NULL),
(255, 'tl', '1130', 2019, NULL, NULL),
(257, 'havo', '1029', NULL, NULL, NULL),
(257, 'vwo', '1029', NULL, NULL, NULL),
(259, 'vwo', '0371', NULL, 2017, 2018),
(261, 'gl', '0414', NULL, NULL, NULL),
(261, 'tl', '0414', NULL, NULL, NULL),
(262, 'havo', '1033', NULL, NULL, NULL),
(262, 'vwo', '1033', NULL, NULL, NULL),
(263, 'gl', '0415', NULL, NULL, NULL),
(263, 'tl', '0415', NULL, NULL, NULL),
(264, 'havo', '1032', NULL, NULL, NULL),
(264, 'vwo', '1032', NULL, NULL, NULL),
(265, 'gl', '0421', NULL, NULL, NULL),
(265, 'tl', '0421', NULL, NULL, NULL),
(266, 'gl', '0422', NULL, NULL, NULL),
(266, 'tl', '0422', NULL, NULL, NULL),
(267, 'havo', '1036', NULL, NULL, NULL),
(267, 'vwo', '1036', NULL, NULL, NULL),
(268, 'havo', '0260', NULL, NULL, NULL),
(268, 'vwo', '0260', NULL, NULL, NULL),
(269, 'havo', '0270', NULL, NULL, NULL),
(269, 'vwo', '0270', NULL, NULL, NULL),
(270, 'havo', '1037', NULL, NULL, NULL),
(270, 'vwo', '1037', NULL, NULL, NULL),
(272, 'bb', '0131', NULL, NULL, NULL),
(272, 'kb', '0131', NULL, NULL, NULL),
(272, 'gl', '0131', NULL, NULL, NULL),
(272, 'tl', '0131', NULL, NULL, NULL),
(272, 'havo', '0131', NULL, NULL, NULL),
(272, 'vwo', '0131', NULL, NULL, NULL),
(273, 'havo', '0400', 2020, NULL, NULL),
(273, 'vwo', '0400', 2021, NULL, NULL),
(274, 'havo', '1022', NULL, NULL, NULL),
(274, 'vwo', '1022', NULL, NULL, NULL),
(275, 'havo', '0311', NULL, NULL, NULL),
(275, 'vwo', '0311', NULL, NULL, NULL),
(276, 'havo', '1021', NULL, NULL, NULL),
(276, 'vwo', '1021', NULL, NULL, NULL),
(277, 'bb', '0125', NULL, NULL, NULL),
(277, 'kb', '0125', NULL, NULL, NULL),
(277, 'gl', '0125', NULL, NULL, NULL),
(277, 'tl', '0125', NULL, NULL, NULL),
(278, 'havo', '1060', NULL, NULL, NULL),
(278, 'vwo', '1060', NULL, NULL, NULL),
(279, 'bb', '1127', NULL, NULL, NULL),
(279, 'kb', '1127', NULL, NULL, NULL),
(279, 'gl', '1127', NULL, NULL, NULL),
(279, 'tl', '1127', NULL, NULL, NULL),
(280, 'havo', '1019', NULL, NULL, NULL),
(280, 'vwo', '1019', NULL, NULL, NULL),
(281, 'bb', '0323', NULL, NULL, NULL),
(281, 'kb', '0323', NULL, NULL, NULL),
(281, 'gl', '0323', NULL, NULL, NULL),
(281, 'tl', '0323', NULL, NULL, NULL),
(282, 'havo', '1034', NULL, NULL, NULL),
(282, 'vwo', '1034', NULL, NULL, NULL),
(287, 'bb', '1112', NULL, NULL, NULL),
(287, 'kb', '1112', NULL, NULL, NULL),
(287, 'gl', '1112', NULL, NULL, NULL),
(287, 'tl', '1112', NULL, NULL, NULL),
(287, 'havo', '1112', NULL, NULL, NULL),
(287, 'vwo', '1112', NULL, NULL, NULL),
(288, 'havo', '0301', NULL, NULL, NULL),
(288, 'vwo', '0301', NULL, NULL, NULL),
(289, 'havo', '1018', NULL, NULL, NULL),
(289, 'vwo', '1018', NULL, NULL, NULL),
(292, 'bb', '0173', NULL, NULL, NULL),
(292, 'kb', '0173', NULL, NULL, NULL),
(292, 'gl', '0173', NULL, NULL, NULL),
(292, 'tl', '0173', NULL, NULL, NULL),
(293, 'gl', '0174', NULL, NULL, NULL),
(293, 'tl', '0174', NULL, NULL, NULL),
(294, 'havo', '1035', NULL, NULL, NULL),
(294, 'vwo', '1035', NULL, NULL, NULL),
(295, 'havo', '1023', NULL, NULL, NULL),
(295, 'vwo', '1023', NULL, NULL, NULL),
(296, 'havo', '1028', NULL, NULL, NULL),
(296, 'vwo', '1028', NULL, NULL, NULL),
(298, 'havo', '1054', NULL, NULL, NULL),
(298, 'vwo', '1054', NULL, NULL, NULL),
(299, 'havo', '1009', NULL, NULL, NULL),
(299, 'vwo', '1009', NULL, NULL, NULL),
(300, 'vwo', '1052', NULL, NULL, NULL),
(301, 'havo', '1004', NULL, NULL, NULL),
(301, 'vwo', '1004', NULL, NULL, NULL),
(302, 'havo', '1002', NULL, NULL, NULL),
(302, 'vwo', '1002', NULL, NULL, NULL),
(303, 'havo', '1003', NULL, NULL, NULL),
(303, 'vwo', '1003', NULL, NULL, NULL),
(304, 'havo', '1017', NULL, NULL, NULL),
(304, 'vwo', '1017', NULL, NULL, NULL),
(305, 'havo', '1094', NULL, NULL, NULL),
(305, 'vwo', '1094', NULL, NULL, NULL),
(306, 'havo', '1006', NULL, NULL, NULL),
(306, 'vwo', '1006', NULL, NULL, NULL),
(307, 'bb', '1108', NULL, NULL, NULL),
(307, 'kb', '1108', NULL, NULL, NULL),
(307, 'gl', '1108', NULL, NULL, NULL),
(307, 'tl', '1108', NULL, NULL, NULL),
(307, 'havo', '1108', NULL, NULL, NULL),
(307, 'vwo', '1108', NULL, NULL, NULL),
(308, 'havo', '0205', NULL, NULL, NULL),
(308, 'vwo', '0205', NULL, NULL, NULL),
(309, 'havo', '1007', NULL, NULL, NULL),
(309, 'vwo', '1007', NULL, NULL, NULL),
(310, 'havo', '1005', NULL, NULL, NULL),
(310, 'vwo', '1005', NULL, NULL, NULL),
(311, 'havo', '1008', NULL, NULL, NULL),
(311, 'vwo', '1008', NULL, NULL, NULL),
(315, 'havo', '1039', NULL, NULL, NULL),
(315, 'vwo', '1039', NULL, NULL, NULL),
(317, 'havo', '1001', NULL, NULL, NULL),
(317, 'vwo', '1001', NULL, NULL, NULL),
(326, 'gl', '1234', 2025, NULL, NULL),
(326, 'tl', '1234', 2025, NULL, NULL),
(327, 'gl', '1919', 2025, NULL, NULL),
(327, 'tl', '1919', 2025, NULL, NULL),
(328, 'gl', '1727', 2025, NULL, NULL),
(328, 'tl', '1727', 2025, NULL, NULL),
(329, 'gl', '2024', 2025, NULL, NULL),
(329, 'tl', '2024', 2025, NULL, NULL),
(330, 'gl', '1823', 2025, NULL, NULL),
(330, 'tl', '1823', 2025, NULL, NULL),
(331, 'gl', '1157', 2025, NULL, NULL),
(331, 'tl', '1157', 2025, NULL, NULL),
(332, 'gl', '2122', 2025, NULL, NULL),
(332, 'tl', '2122', 2025, NULL, NULL),
(333, 'gl', '1518', 2025, NULL, NULL),
(333, 'tl', '1518', 2025, NULL, NULL),
(334, 'gl', '1420', 2025, NULL, NULL),
(334, 'tl', '1420', 2025, NULL, NULL),
(335, 'gl', '1339', 2025, NULL, NULL),
(335, 'tl', '1339', 2025, NULL, NULL),
(336, 'gl', '1159', 2025, NULL, NULL),
(336, 'tl', '1159', 2025, NULL, NULL),
(337, 'gl', '1158', 2025, NULL, NULL),
(337, 'tl', '1158', 2025, NULL, NULL),
(338, 'gl', '1633', 2025, NULL, NULL),
(338, 'tl', '1633', 2025, NULL, NULL),
(339, 'havo', '1154', 2024, NULL, NULL),
(340, 'havo', '1153', 2024, NULL, NULL),
(341, 'havo', '1155', 2024, NULL, NULL),
(342, 'bb', '1132', 2021, NULL, NULL),
(342, 'kb', '1132', 2021, NULL, NULL),
(342, 'gl', '1132', 2021, NULL, NULL),
(342, 'tl', '1132', 2021, NULL, NULL),
(342, 'havo', '1132', 2021, NULL, NULL),
(342, 'vwo', '1132', 2021, NULL, NULL),
(344, 'bb', '1168', NULL, 2026, NULL),
(344, 'kb', '1168', NULL, 2026, NULL),
(344, 'gl', '1168', NULL, 2026, NULL),
(344, 'tl', '1168', NULL, 2026, NULL),
(345, 'bb', '0153', NULL, 2028, 2029),
(345, 'kb', '0153', NULL, 2028, 2029),
(345, 'gl', '0153', NULL, 2028, 2029),
(345, 'tl', '0153', NULL, 2028, 2029),
(346, 'havo', '1024', NULL, NULL, NULL),
(346, 'vwo', '1024', NULL, NULL, NULL),
(347, 'havo', '1025', NULL, NULL, NULL),
(347, 'vwo', '1025', NULL, NULL, NULL),
(348, 'vwo', '1026', NULL, NULL, NULL),
(349, 'havo', '1027', NULL, NULL, NULL),
(349, 'vwo', '1027', NULL, NULL, NULL),
(350, 'vwo', '1163', 2026, NULL, NULL),
(351, 'havo', '1164', 2026, NULL, NULL),
(351, 'vwo', '1164', 2026, NULL, NULL),
(352, 'havo', '1165', 2026, NULL, NULL),
(352, 'vwo', '1165', 2026, NULL, NULL),
(353, 'havo', '1166', 2026, NULL, NULL),
(353, 'vwo', '1166', 2026, NULL, NULL);

COMMIT;
